### ISSUE TITLE
Badge url has missing host 

### ISSUE THREAD

**Issue by daneroo** [gojp/goreportcard#107]
From the report site, [like this for example](https://goreportcard.com/report/github.com/gojp/goreportcard);
When you click on the badge to reveal the badge image url, and/or markdown for the badge,

The resulting image url, and report url have an empty host portion

Visually:
[![Go Report Card](https:///badge/github.com/gojp/goreportcard)](https:///report/github.com/gojp/goreportcard)
 should be:
[![Go Report Card](https://goreportcard.com/badge/github.com/gojp/goreportcard)](https://goreportcard.com/report/github.com/gojp/goreportcard)

Textually
`https:///report/github.com/gojp/goreportcard` should be
`https://goreportcard.com/report/github.com/gojp/goreportcard`
and
`https:///badge/github.com/gojp/goreportcard` should be
`https://goreportcard.com/badge/github.com/gojp/goreportcard`

**Comment by Depado** [comment]
Same problem here.

**Comment by hermanschaaf** [comment]
I'm guessing it was brought on by the changes in https://github.com/gojp/goreportcard/pull/97, and I missed it. Will fix soon, thanks for reporting!

**Comment by shawnps** [comment]
Thanks @trinchan for the fix

**Comment by daneroo** [comment]
Nice work, thanks for the quick fix.
