### ISSUE TITLE
support for local filesystem projects

### ISSUE THREAD

**Issue by Oppodelldog** [gojp/goreportcard#109]
Hi,
This is a really nice project combining all those good go code quality tools and I would like to integrate this project into our Jenkins to produce those fine reports on every build.
Therefore I would like to ask if you are open for pull-requests that would enable scanning of local files as well.

I would not want to integrate that functionality into the existing  webapplication but maybe into a cmd-line parameter. I would split out the filesystem scanning part of the checking into a new separate method to be able to call it just for a directory with a reponame/url.

What do you think about that idea?

**Comment by shawnps** [comment]
@Oppodelldog I believe someone worked on something like this, I haven't checked the code:

https://github.com/gojp/goreportcard/issues/28

Do you want the scores in your Jenkins, or just the linter results? If you just want the linter results, I'd recommend using Go Meta Linter: https://github.com/alecthomas/gometalinter

**Comment by Oppodelldog** [comment]
Thanks, I will follow #28.
