### ISSUE TITLE
go_vet reports unknown identifier in example code

### ISSUE THREAD

**Issue by arthurwhite** [gojp/goreportcard#113]
For example, the [github.com/gowww/compress](https://goreportcard.com/report/github.com/gowww/compress) package.

The package name `compress` is suffixed with `_test` inside the [`example_test.go`](https://github.com/gowww/compress/blob/master/example_test.go#L1) file.
That's maybe why this `go vet` doesn't recognize the identifier reference.

But [it should](https://blog.golang.org/examples).
And locally, my `go vet github.com/gowww/compress` returns no error.

**Comment by shawnps** [comment]
@arthurwhite that is strange behavior indeed. 

i can't reproduce it on my local, but i see it failing on the go report card server. i opened a ticket with gometalinter, will see what the author says:

https://github.com/alecthomas/gometalinter/issues/108

**Comment by shawnps** [comment]
Looks like it's not `gometalinter` but rather something strange going on with `vet` on the server...I'll try to investigate further soon

**Comment by shawnps** [comment]
Weird, `go vet` passes on command line on my local, but fails with the same errors when running Go Report Card locally.

**Comment by hectorj** [comment]
What go versions are you guys using?

I have a similar problem in one of my projects: it works with Go 1.5.X, but fails with Go 1.6.X

**Comment by arthurwhite** [comment]
Personally, I have the `1.6.2 darwin/amd64` installed with Homebrew.

What is even weirder is that Go Report Card returns a 100% success for another package ([github.com/gowww/log](https://goreportcard.com/report/github.com/gowww/log)) which have exactly the same "template".

**Comment by arthurwhite** [comment]
I just pushed a new commit and Go Report Card fails for this package too. 💣 

 |  example_test.go
--- | ---
Previously | [`e31412b`](https://github.com/gowww/log/blob/e31412b00154959aaefdc02264d1581803dee23f/example_test.go)
Now | [`a2e97ea`](https://github.com/gowww/log/blob/a2e97eaf65b509da6b6fdddf1203a3aaa4b324de/example_test.go)

**Comment by db47h** [comment]
Same for this package: https://goreportcard.com/report/github.com/db47h/cache 

I use go 1.7 and go-tip as test code is not compatible with go <1.7,

**Comment by korthaj** [comment]
Maybe this is a caching issue? In my case, I got the false positive

> radix/example_test.go
> Line 8: error: ExampleSortSlice refers to unknown identifier: SortSlice (vet)

Perhaps go vet is looking at the new version of the file example_test.go and an older cached version of the file that actually contains SortSlice. I did, in fact, use goreportcard earlier, when the new function and the new test didn't yet exist.

**Comment by shawnps** [comment]
@korthaj unfortunately I don't believe it's a caching issue but rather an issue with `go tool vet` itself. I just ran it manually against your repo and I get the error:

```
$ go tool vet *.go
example_test.go:8: ExampleSortSlice refers to unknown identifier: SortSlice
```

`gometalinter` uses `go tool vet` rather than `go vet`, I believe for historical reasons. Someone brought up a similar issue here:

https://github.com/alecthomas/gometalinter/issues/218

If I can find a way to have `gometalinter` use `go vet` instead of `go tool vet`, it might be fixable.

**Comment by arthurwhite** [comment]
> If I can find a way to have gometalinter use go vet instead of go tool vet, it might be fixable.

At first glance, just calling `go vet` instead of `gometalinter` at [check/go_vet.go:21](https://github.com/gojp/goreportcard/blob/a16b0104fa367218ab1cb8faa0ad175eb81a5ce2/check/go_vet.go#L21) should do the fix.  
'Doesn't work like this?

**Comment by arsham** [comment]
I'm experiencing the same problem [here](https://github.com/arsham/expvastic/blob/af5eeb25406ad2597cdd0184aff46b60f712c525/token/example_test.go#L15)
 from [this report](https://goreportcard.com/report/github.com/arsham/expvastic). The [identifier](https://github.com/arsham/expvastic/blob/af5eeb25406ad2597cdd0184aff46b60f712c525/token/token.go#L35) is defined and on local version it reports no issues.

**Comment by GoLangsam** [comment]
Same experience with my new repo [github.com/GoLangsam/template](https://goreportcard.com/report/github.com/GoLangsam/template) using unnamed import aka `import . "html/template"` (as does standard `html/template/template_test.go`).

Local use of `go vet` and `go tool vet` remains silent.

Local use of `gometalinter` gives same "noise"!
Local use of `goreportcard` (under Windows - mind You :-) with latest `gometalinter` gives same "noise"!

After patching `check/go_vet.go` to:

	return GoTool(g.Dir, g.Filenames, []string{"go", "tool", "vet"})

things are fine :-)

(except for small and unrelated Windows-issues - and that's a separate story!)

**Comment by shawnps** [comment]
I will take a look at this soon.

**Comment by GoLangsam** [comment]
Looking @ [alecthomas/gometalinter#218](https://github.com/alecthomas/gometalinter/issues/218) I feel that they'r pushing this off to the go tool chain. Thus, there is no hope for any quick solution soon.

Having browsed `cmd/go/main.go` and friends such as `pkg.go` I understand the trouble of the go team in supporting the variety of usages of their tools.

I also understand and experience: the *best* (if I may say so) way to point to packages is ***inside*** a workspace (`$GOPATH` set) and via `import-path-of-package\...`.

Looking @ Your implementation, I see:
- You supply individual filenames ... (to be discussed separtely)
- nowhere do not (attempt to) touch `$GOPATH`

Thus: I just set my `$GOPATH` the `_repo` - and: ***All is fine and copathetic*** :-) :-) :-)

So, I'd humbly like to recommend: ***Stay far away from non-standard usage of package pointers when using go tools!***

(Note: There's even a myriad of issues, blogs etc. around explaining very good reasone as of *why* some usage styles ***have*** to behave in ways unexpected to the naive and innocent user.)

**Comment by GoLangsam** [comment]
Having found this, I'll have to read and think a little more in order to come up with a feasible solution which suits Your product.

**Comment by GoLangsam** [comment]
@shawnps @hermanschaaf
 
[here we go](https://github.com/gojp/goreportcard/pull/209) - Sorry for keeping You waiting :-)

**Comment by stevenh** [comment]
This is still an issue, I've raised it against go vet:
https://github.com/golang/go/issues/22530

**Comment by stevenh** [comment]
As [suggested by Russ Cox](https://github.com/golang/go/issues/22530#issuecomment-342286322) if the calls to ```go tool vet``` are replaced with calls to ```go vet``` examples pass.

**Comment by breml** [comment]
I have a similar problem with my package [logstash-config](https://github.com/breml/logstash-config).

Locally `go vet .`, `go tool vet .` as well as `gometalinter .` do not return an error. I use `go version go1.10.1 linux/amd64`. On goreportcard.com the following error is shown (https://goreportcard.com/report/github.com/breml/logstash-config):

```
logstash-config/logstash_config_test.go
Line 12: error: ExampleParseReader refers to unknown identifier: ParseReader (vet)
```

The `ParseReader` function is defined in `logstash_config.go`, which is a generated file and therefore has the comment `// Code generated by pigeon; DO NOT EDIT.`, which instructs the go tools to not perform linting and vetting on this file (see https://github.com/golang/go/issues/13560#issuecomment-288457920 for details).

**Comment by rameshvk** [comment]
I hit this regularly when working with examples (with a _test package name).  Gometalinter will pass locally but goreportcard reports these false warnings.  In most cases, I am able to change the example to use the same package name but sometimes that causes import cycles....

**Comment by mrinalwadhwa** [comment]
Have the same problem in this report https://goreportcard.com/report/github.com/ockam-network/did

Locally `go vet github.com/ockam-network/did` returns no errors.

**Comment by blockloop** [comment]
I was able to reproduce the error by running `go vet <file>` against only the example_test file rather than against the whole repo.

```
λ go vet example_scanner_test.go
# command-line-arguments_test
./example_scanner_test.go:33:1: ExampleRow refers to unknown identifier: Row
./example_scanner_test.go:55:1: ExampleRow_scalar refers to unknown identifier: Row
./example_scanner_test.go:74:1: ExampleRows refers to unknown identifier: Rows
./example_scanner_test.go:96:1: ExampleRows_primitive refers to unknown identifier: Rows
- master
λ go vet github.com/blockloop/scan
- master
λ
```

**Comment by ljmsc** [comment]
hi,
i had the same issue. Please note the naming convention described here:
https://golang.org/pkg/testing/#hdr-Examples
