### ISSUE TITLE
can we be smarter when go get fails?

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#115]
I've seen this happen a few times: when trying to `go get` something, one of the dependencies (which is already on the server) is messed up somehow:

```
2016/04/06 04:28:51 Go getting "github.com/appleboy/gofight"...
2016/04/06 04:28:56 Go get error log: # cd /home/shawn/mygo/src/github.com/gojp/goreportcard/repos/src/github.com/labstack/echo; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/labstack/echo: exit status 128
```

and the whole thing fails. What I do in this case is I go to the folder of that dependency in the GOPATH and just delete it. I can't do that forever, so we need to figure out why this is even happening in the first place and/or automate fixing it.

**Comment by hermanschaaf** [comment]
I think you are referring to the same issue as https://github.com/gojp/goreportcard/issues/90 ?

**Comment by shawnps** [comment]
@hermanschaaf ah yeah probably. closing
