### ISSUE TITLE
Ignore generated code

### ISSUE THREAD

**Issue by prashantv** [gojp/goreportcard#116]
Something similar to:
https://github.com/github/linguist/blob/master/lib/linguist/generated.rb

I'm seeing files that aren't ignored that are generated in my repository:
https://github.com/uber/tchannel-go/blob/master/trace/thrift/gen-go/tcollector/ttypes.go
https://github.com/uber/tchannel-go/blob/master/examples/thrift/gen-go/test/tchan-test.go

Comments like "Autogenerated by" or "@generated" or "Code generated by" usually appear at the top of generate code files that should be ignored.

**Comment by peterbourgon** [comment]
Here are some more example files, Thrift and protobufs

- https://github.com/go-kit/kit/tree/master/examples/addsvc/thrift/gen-go/add
- https://github.com/go-kit/kit/blob/master/examples/addsvc/pb/add.pb.go

**Comment by alkchr** [comment]
Any reason why generated files should be exempt from the requirement to follow Go style guide?

**Comment by peterbourgon** [comment]
In an ideal world, code generators will produce stylistically valid Go code. But in our practical world, I think you will never convince the e.g. Thrift compiler folks to care about Go naming conventions or idioms. They abide their own conventions, which typically need to remain coherent across multiple target languages.

**Comment by alkchr** [comment]
Isn't the function of goreportcard to encourage Go's conventions (not someone else's ones)? If in real world you're not able to follow the accepted style guide, that's OK, you just get a lower score. And that's fair.
In practical world there is a single complete implementation of yaml. It is transpiled from C and half of its code looks as follows:
```go
func yaml_emitter_set_writer_error(emitter *yaml_emitter_t, problem string) bool {
	emitter.error = yaml_WRITER_ERROR
	...
}
```
Just because of that should goreportcard conclude the code is 100% conventional and grade it as A+?

**Comment by peterbourgon** [comment]
> Just because of that should goreportcard conclude the code is 100% conventional and grade it as A+?

IMO, the YAML project should get a low score, but projects which incidentally use the YAML project should not be penalized for it.

Similarly, if I want to provide Thrift bindings in my project, I have to use the official Thrift IDL compiler to produce Go code. That generated code is incidental to my project, I didn't write it, I'm not invested in it, I don't particularly care about it. I don't think I should be penalized for the Thrift developer's bad practice. Of course, you may disagree.

**Comment by shawnps** [comment]
I see where both sides are coming from. But I think as we already skip some of these files, and many people have asked for this, we'll end up skipping code generated by Thrift for the time being. I would love to see issues opened with whatever tools are generating the code to make it more idiomatic. In the future we can remove the logic that skips generated code if we decide to.

**Comment by shawnps** [comment]
For reference on what we skip already:

https://github.com/gojp/goreportcard/blob/16b0c80f9fcf22add65937fdd3a6f86676fcefee/check/utils.go#L14

**Comment by hermanschaaf** [comment]
We now check for certain comments, like `"// generated"` in the first line of the file:

https://github.com/gojp/goreportcard/blob/25f1fe9648d5aa4c06118317a42ecb523581a0b0/check/utils.go#L15-L17

Unfortunately gometalinter doesn't allow us to either skip individual files or run on individual files, so we currently run the checks on all files, and then filter out the unwanted results. This is a situation that we can hopefully improve upon in the future.

Thanks all for reporting, and let us know if you have any further issues!
