### ISSUE TITLE
gofmt report seems incorrect

### ISSUE THREAD

**Issue by dnaeon** [gojp/goreportcard#118]
The report from gofmt seems incorrect.

Repo in question:

 - https://github.com/dnaeon/gru

Generated report from GoReportCard:

 - https://goreportcard.com/report/github.com/dnaeon/gru#gofmt

My files are already gofmt'ed, so nothing reported on my system.

```bash
$ gofmt -s -l .
```

Also these lines here are not correct.

```bash
Gofmt formats Go programs. We run gofmt -s on your code, where -s is for the "simplify" command
gru/gructl/command/validate.go
Line 1: expected 'package', found 'EOF':1::warning: file is not gofmted (gofmt)
```

Since my file contains `package` already.

**Comment by shawnps** [comment]
@dnaeon Thanks for the report. I believe this was a side effect of disk space running out on the Go Report Card server. I think the `go get` wasn't able to complete because of lack of space, and the repo on disk was left in a weird state. I refreshed and it looks like it works now.

**Comment by dnaeon** [comment]
@shawnps thanks for looking into this one!
