### ISSUE TITLE
Check your Golint version

### ISSUE THREAD

**Issue by bep** [gojp/goreportcard#121]
See

https://goreportcard.com/report/github.com/bep/gr

And

https://play.golang.org/p/D-vWPKGnV2

Your GoLint complains about:
```
Line 42: warning: should omit type gr.Modifier from declaration of var itemStatus; it will be inferred from the right-hand side (golint)
```

But, as in the example, the code won't compile without the type in the declaration, and my current GoLint setup does not complain about this.

**Comment by shawnps** [comment]
@bep could you provide an example repo please?

**Comment by shawnps** [comment]
@bep nvm I see `bep/gr`in recent reports.

**Comment by bep** [comment]
Sorry ... yes, I messed up with my copy-pastes. bep/gr it is.

**Comment by shawnps** [comment]
@bep I updated golint on the server as well as on my local and they both return the result that you pasted above. 

You're right however that the code doesn't compile without `gr.Modifier`. Not quite sure what the best thing is to do here...maybe it's a bug in golint?

**Comment by hermanschaaf** [comment]
Could it be a gometalinter thing? I'm also wondering what version of Go @bep is running?

**Comment by shawnps** [comment]
@hermanschaaf I ran `golint` directly, not with `gometalinter`. 

I'm going to try increasing this next:

```
  -min_confidence float
    	minimum confidence of a problem to print it (default 0.8)
```

I checked the golint source and it looks like the error might only get printed for 0.8 confidence

**Comment by hermanschaaf** [comment]
@shawnps Ah okay yeah, that sounds good.

**Comment by shawnps** [comment]
Increasing the `min_confidence` makes it not report that anymore...now to see if we can add that to the  `gometalinter` call

**Comment by shawnps** [comment]
@bep try again, we increased the `min_confidence` for `golint` and it shouldn't report that error anymore.

**Comment by bep** [comment]
100% score... Thanks.

For the record, none of my GoLints complains with the default setting (= min_confidence = 0.8).

**Comment by shawnps** [comment]
@bep thanks yeah, not sure what the difference is without knowing more about your system and if your golint is up to date, etc.
