### ISSUE TITLE
check/license: Allow LICENSE.{name}.{ext} 

### ISSUE THREAD

**Issue by hansrodtang** [gojp/goreportcard#124]
For repositories that have dual-licensed code adding the license name (and optionally a file extension) to the license file is a somewhat common pattern. It would be nice if you could detect licenses that match this pattern.

Examples: `LICENSE.BSD.md` and `license.gpl`

Same goes for COPYING and possibly other prefixes. The rule that would cover most cases is probably to allow all files which have the current rules as their prefix.

**Comment by hermanschaaf** [comment]
Thanks for reporting! I suppose there is no harm in adding this as an option, but I would argue that the LICENSE.{name}.md is not as common a pattern as you might suppose:

119 repos use [LICENSE.BSD.md](https://github.com/search?utf8=%E2%9C%93&q=filename%3ALICENSE.BSD.md&type=Code&ref=searchresults)

903 use [LICENSE.MIT.md](https://github.com/search?utf8=%E2%9C%93&q=filename%3ALICENSE.MIT.md&type=Code&ref=searchresults)

111 use [LICENSE.GPL.md](https://github.com/search?utf8=%E2%9C%93&q=filename%3ALICENSE.GPL.md&type=Code&ref=searchresults)

About ~1,000 repos on Github use this in total, compared to the 1,753,326 reported by the search function to use `LICENSE.md`.

LICENSE.GPL, LICENSE.MIT, etc are quite common, as @hansrodtang said, with millions of repos reported to use that format. Anyway, it should just be a matter of adding this to the list in https://github.com/gojp/goreportcard/blob/16b0c80f9fcf22add65937fdd3a6f86676fcefee/check/license.go#L25-L29, and have it conform to the format of the `find` command.

**Comment by hansrodtang** [comment]
The suffix was as I mentioned just optional and I included all cases when counting popularity of the pattern.

Adding `LICENSE.GPL` and `LICENSE.MIT` etc. sounds like a fine temporary fix but I think it is more correct to allow any suffix.
Adding more and more special cases as they are discovered could end up being tedious for something that could be fixed pretty much once and for all with adding prefix matching. That would allow all possible combinations of license/copying/copyright{.name}{.ext} and remove special cases for extensions like .md and .txt for the existing rules.

I would be happy to contribute the change in question if such an improvement is welcomed. Let me know! 😃

**Comment by hermanschaaf** [comment]
Oh yes, sorry that my message was unclear; I agree we should allow any suffix or extension, and you should be able to do that by adding to the existing list of allowed terms in the format specified by the `find` command. I imagine something like `"license.*"` and `license.*.*` (+copyright, copying, etc) should cover it. Would just need to be tested as well, but I don't think there's much that can go wrong here.

I do suppose we need to be a little careful; if someone has a file named `license.go`, for example, it's probably not their real license file. But I'm okay with that kind of edge case to keep the code simple.

@hansrodtang Thanks! If you make the change I think @shawnps will agree that we can merge it in :+1:

**Comment by shawnps** [comment]
The only thing I can think of going wrong is if we use wildcards and the repo has a file called `license.go` but not a `LICENSE`, it will be counted as having a license, right?

**Comment by hermanschaaf** [comment]
@shawnps Yeah, that's the only thing I can think of. Like I said, I'm okay with that edge case if it allows for much simpler code.

**Comment by hansrodtang** [comment]
Since this project is meant for Go projects a `license*.go` (also covers `license*_test.go`) is probably the only one we have to be careful about, and it should not be hard to ignore all files with a `.go` extension.

Is it okay to experiment with alternate implementations using the likes of `path/filepath.Walk`? Or is there a performance (or other) reason you are using `find`?

**Comment by hermanschaaf** [comment]
Yeah, feel free to experiment with alternate implementations, I don't think we have a particularly good reason to keep using `find`, unless @shawnps can think of one?

**Comment by shawnps** [comment]
Oh no that would be great, feel free @hansrodtang

**Comment by shawnps** [comment]
@hansrodtang https://goreportcard.com/report/github.com/hansrodtang/randomcolor#license looks like it worked, thanks
