### ISSUE TITLE
The goreportcard site appears to be down

### ISSUE THREAD

**Issue by dnaeon** [gojp/goreportcard#127]
Check https://goreportcard.com/report/github.com/gojp/goreportcard (or any other repo for that matter)

Results in:

502 Bad Gateway

nginx/1.4.6 (Ubuntu)

**Comment by hermanschaaf** [comment]
Thanks for reporting! We'll have to do a postmortem on this, but the site is back up for now, albeit without the previous boltdb database with recent repos and high scores. I believe @shawnps has access to a relatively recent backup of that we can roll back to.

**Comment by hermanschaaf** [comment]
Okay, I rolled back to a database from a few weeks ago, that's probably fine for now. This really was quite a serious event, we'll need to figure out how to prevent it from happening again.

**Comment by hermanschaaf** [comment]
Since the site is back up now, I'll close this issue and open a new one to discuss the bug that caused it.

**Comment by papakai** [comment]
Site is again down.

**Comment by hermanschaaf** [comment]
Thanks - I'm unable to take a look at this right now, but I'll try and resurrect it ASAP

**Comment by mitinarseny** [comment]
Can't generate report for my project. Can you help, please?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10659110/59791638-3f5c0880-92db-11e9-8ee0-73c89a0ac15a.png">
