### ISSUE TITLE
Goreportcard source directory can get deleted in certain edge case

### ISSUE THREAD

**Issue by hermanschaaf** [gojp/goreportcard#128]
It seems that in some edge case, when we are deleting cached repos because of git history changes, it can happen that the goreportcard directory itself gets deleted, along with the bolt database. This is why the site went down as reported in https://github.com/gojp/goreportcard/issues/127 

I thought we covered all the edge cases when we wrote the cache invalidation logic, but it seems like we not.

**Comment by shawnps** [comment]
@hermanschaaf we haven't seen this for a long time - closing this and we can reopen if we notice it happening again.
