### ISSUE TITLE
Commit 43b4abfd9a7a4ac3b7e6d6d88ab32062fb52a1ac break skipping content of vendor folder in result

### ISSUE THREAD

**Issue by artemnikitin** [gojp/goreportcard#129]
In last commit 43b4abfd9a7a4ac3b7e6d6d88ab32062fb52a1ac issue was introduced. Currently, rating take in mind content of `vendor` folder, while previously don't. I tried to revert specified commit locally and it fixes problem for me.
Unfortunately at this moment, I wasn't been able to understand there is a problem in sources and made a pull request with fix

**Comment by shawnps** [comment]
thanks @artemnikitin, I'll revert that commit and @hermanschaaf and I will investigate more

**Comment by shawnps** [comment]
@artemnikitin we found the root of the problem and we'll fix it soon. Thanks for reporting

**Comment by artemnikitin** [comment]
Ok, I see that issue was already fixed. I will close issue. Thanks for quick response )
