### ISSUE TITLE
make "github.com/foo/bar" part of "Report for github.com/foo/bar" title a link on report page

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#131]
![screen shot 2016-05-30 at 4 19 20 pm](https://cloud.githubusercontent.com/assets/80111/15642426/4accf31e-2682-11e6-8d35-5306e0e1fd4c.png)

I'd like to be able to click that "github.com/golang/crypto" text and go directly to the page. Let me know if you prefer without a link @hermanschaaf as it's not a huge deal

**Comment by hermanschaaf** [comment]
Yes we should do this! But we need to make sure it only has this behavior for Github, bitbucket (?), etc
