### ISSUE TITLE
Idea: Run errcheck on project

### ISSUE THREAD

**Issue by MetalMatze** [gojp/goreportcard#132]
Hey, I really like [errcheck](https://github.com/kisielk/errcheck) and think it would be awesome to integrate it into goreportcard.
Just want to get some feedback for this.

Thanks

**Comment by hermanschaaf** [comment]
Sounds good to me! We will surely want to ignore some error checks by default, like the error returned by `fmt.Print`. I've never used errcheck myself, so do you have any thoughts on sensible functions / packages to ignore?

Other than that, I don't see any major issues with adding this. Thanks for the suggestion, and anyone feel free to open a pull request :smile:

**Comment by hermanschaaf** [comment]
Closed by https://github.com/gojp/goreportcard/pull/137 (but not deployed yet)
