### ISSUE TITLE
HTTP 400 - cannot `go get` repository

### ISSUE THREAD

**Issue by mannkind** [gojp/goreportcard#142]
I'm getting a HTTP 400 error via goreportcard when checking my [tweetdelete](http://github.com/mannkind/tweetdelete) repository.  
e.g. <https://goreportcard.com/checks?repo=github.com%2Fmannkind%2Ftweetdelete>

I'm pretty new to Go, so perhaps I setup the repository incorrectly. However, I do have two other repositories (<http://github.com/mannkind/mysb> and <http://github.com/mannkind/dashbtn>) setup _very_ similarly that goreportcard seems to check without an issue.

Is this error because of something in my repository or is it something that you have to fix?

Thanks for making goreportcard!

**Comment by hermanschaaf** [comment]
@mannkind Thanks for the message, but it seems [fine to me now]( https://goreportcard.com/report/github.com/mannkind/tweetdelete). Could have been a temporary issue, or more likely an invalid import in your project preventing it from being `go get`-able. I'm thinking about ways we can make this more forgiving, or at least make the error message more informative. 

For future readers: my advice is to check whether you can `go get` your repo yourself. If you can't, check the error message. If you still can't use goreportcard, it's likely that one of the dependencies was cached on our server but then git rebased, which causes `go get` to fail. If this happens, let us know and we can fix it manually until we have time to implement a permanent solution.

**Comment by mannkind** [comment]
Interesting. Glad it's working now!

**Comment by hermanschaaf** [comment]
Me too :smile_cat:
