### ISSUE TITLE
Check license in parent directories

### ISSUE THREAD

**Issue by creack** [gojp/goreportcard#143]
When checking the report of a subpackage, the license check fails while the project is licensed in at the directory's root.

I think it would be interesting to check the parent directories for the License file.

**Comment by kare** [comment]
I've got exactly the same issue!

**Comment by shawnps** [comment]
@creack @kare could one of you provide an example just for reference? Just so I have something to base tests on

**Comment by kare** [comment]
Here's one:
- https://github.com/kare/vanity/
- https://github.com/kare/vanity/tree/master/cmd/vanity

**Comment by shawnps** [comment]
Looks like kare's repository contains a LICENSE in the root now. Sorry, I think it's easiest for us to just check the root dir for now. We'd certainly look at a PR if one were to be made though.
