### ISSUE TITLE
badge in project page doesn't update

### ISSUE THREAD

**Issue by ccding** [gojp/goreportcard#145]
see https://github.com/ccding/go-stun
and https://goreportcard.com/report/github.com/ccding/go-stun

The go report letters are different in the two pages. Cannot figure it out.

**Comment by hermanschaaf** [comment]
Looks the same to me (both are A+) - you are probably seeing a cached image. Both your browser and Github aggressively caches images, and it can take up to 48 hours to update on its own.

Try doing a [hard refresh](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/) and let me know if that doesn't fix it!

![screenshot from 2016-07-29 09 25 29](https://cloud.githubusercontent.com/assets/1121616/17234785/6c4172f2-556e-11e6-88b9-b5165a15e73e.png)

**Comment by hermanschaaf** [comment]
We recently improved the caching behavior of our badges and started hosting them ourselves (not on shields.io). From now on this should not be an issue, as long as Github honors the no-cache header.
