### ISSUE TITLE
There was an error processing your request: Could not go get the repository.

### ISSUE THREAD

**Issue by dnaeon** [gojp/goreportcard#146]
Hi,

Seems I'm not able to refresh the stats for my project.

-  https://goreportcard.com/report/github.com/dnaeon/gru

Could you please look into this one?

Thanks!

**Comment by hermanschaaf** [comment]
Hi! I can't `go get` the repo locally; it fails with the error:

```
# github.com/dnaeon/gru/utils
../../../dnaeon/gru/utils/file.go:26: undefined: user.Group
```

`Could not go get the repository` can happen for a number of reasons (there is a known bug), but this error is likely the issue in this particular case.

**Comment by dnaeon** [comment]
Hi,

Thanks for checking! Indeed that must be it, since I'm using golang tip. On a side note what is the golang version that gorepprtcard uses?

Thanks,
Marin

**Comment by hermanschaaf** [comment]
@dnaeon Our server is currently running go version go1.6.2 linux/amd64
