### ISSUE TITLE
make and document an API

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#15]
this is way in the future probably but would be cool to expose an API for people to hit

**Comment by shawnps** [comment]
this has been requested a couple of times. should consider exposing an API and documenting it in the README or on the site itself

**Comment by shawnps** [comment]
This sort of came up in an issue here https://github.com/avelino/awesome-go/issues/683 

Would be nice to at least document the /checks endpoint so people don't need to find it themselves.

**Comment by adelevie** [comment]
Big :+1: to an API. For [18F's](https://18f.gsa.gov/) [micro-purchase project](https://micropurchase.18f.gov/), we use various automated tests to help ensure the quality of code submitted for tiny government contracts. If we ever required a vendor to create a golang project/repo, this would be a wonderful tool to use. We could set a minimum threshold grade as part of the acceptance criteria.
