### ISSUE TITLE
Error after repo has had a force-push

### ISSUE THREAD

**Issue by DanielOaks** [gojp/goreportcard#150]
Hi GRC team,

I'm having an issue with one of my repositories where I can no longer run GoReportCard over it. I get this error:
>There was an error processing your request: Could not download the repository.

What I did beforehand was that I pushed a change to my repo, ran GRC on it. GRC pointed out a bug, which is awesome. I fixed the bug, modified the original commit with `git commit --amend`, and force-pushed the new commit to the repo.

I think it's having some troubles pulling the new version of the repo because of that force-push (rough guess, haven't actually looked too far into it).

If you guys could take a look at this it'd be much appreciated, GRC is awesome! Thanks for the cool tool.

For reference, my repo is [github.com/DanielOaks/oragono](https://goreportcard.com/report/github.com/DanielOaks/oragono).

**Comment by shawnps** [comment]
Hi @DanielOaks

Thanks for the detailed report and glad you like GRC! 

Unfortunately I'm not able to take a look at fixing this for a few hours as I'm away from my PC for a while. Your theory about force push breaking it sounds like a good start, we've seen some weirdness when people force pushed before. 

We'll try to think of a better way to handle that, sorry! 

I or Herman will update this ticket after we've taken a look at the server.

**Comment by DanielOaks** [comment]
Hi Shawn,

All good! Thanks for the quick response, it's much appreciated. Don't stress, I'm not in any particular hurry – enjoy the weekend :)

**Comment by shawnps** [comment]
@DanielOaks It should work now. I deleted the repo we had on disk and re-generated the report. I'm going to leave this ticket open though because we should figure out a better way to handle this.

For posterity:

```
git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 9 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean
```

```
2016/08/14 01:55:45 Checking repo "github.com/DanielOaks/oragono"...
2016/08/14 01:55:45 Update https://github.com/DanielOaks/oragono
cd repos/src/github.com/DanielOaks/oragono
git pull --ff-only
# cd repos/src/github.com/DanielOaks/oragono; git pull --ff-only
From https://github.com/DanielOaks/oragono
   154809d..31757a6  master     -> origin/master
fatal: Not possible to fast-forward, aborting.
2016/08/14 01:55:46 ERROR: from newChecksResp: could not clone repo: exit status 128
```

**Comment by DanielOaks** [comment]
Nice. Thank you very much for the quick turnaround, it's much appreciated!
