### ISSUE TITLE
[There was an error processing your request: Could not download the repository]

### ISSUE THREAD

**Issue by shiyanhui** [gojp/goreportcard#151]
When I click the **refresh button**, it shows the **There was an error processing your request: Could not download the repository.** message.

url is https://goreportcard.com/report/github.com/shiyanhui/dht

**Comment by hermanschaaf** [comment]
Hi @shiyanhui 

Thanks for the report. I fixed the error manually on the server for your case. And I will look into solving it properly later. As long as you don't rebase the git repo again, it should be okay. 

Logs to fix this later:

```
2016/08/15 05:55:24 Checking repo "github.com/shiyanhui/dht"...
2016/08/15 05:55:24 Update https://github.com/shiyanhui/dht
cd repos/src/github.com/shiyanhui/dht
git pull --ff-only
# cd repos/src/github.com/shiyanhui/dht; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
2016/08/15 05:55:25 Failed to download "https://github.com/shiyanhui/dht" (exit status 128), trying again...
2016/08/15 05:55:25 Update https://github.com/shiyanhui/dht
cd repos/src/github.com/shiyanhui/dht
git pull --ff-only
# cd repos/src/github.com/shiyanhui/dht; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
2016/08/15 05:55:25 ERROR: from newChecksResp: could not clone repo: exit status 128
```

**Comment by hermanschaaf** [comment]
It seems like the attempt to delete the broken repo must fail for some reason.

**Comment by shiyanhui** [comment]
OK, thanks!

**Comment by hermanschaaf** [comment]
Okay, hopefully [this commit](https://github.com/gojp/goreportcard/commit/09453248dc6ffd925f6185a6217f66d6382c3fc2) solves the problem [once and for all](https://www.youtube.com/watch?v=gONcDfFrPis) :)

The mistake was to use `Remove` on a non-empty directory, when it should have been `RemoveAll`. We also weren't checking the error there. It would be nice to get the `errcheck` test working, then we might have spotted that earlier.
