### ISSUE TITLE
Check for vendor folder

### ISSUE THREAD

**Issue by rkulla** [gojp/goreportcard#152]
Check if there is a `vendor` folder. Just the folder and not necessarily what tool they used to create it. Perhaps also check for anything that follows the [vendor spec](https://github.com/kardianos/vendor-spec), such as the presence of a vendor.json file.

For libraries, check that there is _not_ a vendor folder present. This would likely be based on first checking to see that aren't any instances `package main`. This would also be good in conjunction with #140.

**Comment by dlsniper** [comment]
Hi, one problem, how do you distinguish between libs which have an example by having a package main in a folder?

**Comment by dlsniper** [comment]
For example: https://github.com/aws/aws-sdk-go/blob/master/example/service/s3/listObjects/listObjects.go

**Comment by rkulla** [comment]
@dlsniper: Hmm. Since goreportcard tends to use existing go tools for scanning things, do you know of any that solve that problem already (or any workarounds)?

**Comment by hermanschaaf** [comment]
@dlsniper Good point! I like this idea overall, we just need to consider the edge cases.

Also, not all main packages will necessarily require a vendor folder (e.g. if there are no external dependencies.) So we would need to check the imports in the package, and see if any of them are external and not part of the Go standard library. If so, require a vendor folder containing those dependencies. The example @dlsniper brought up can maybe be handled by not requiring a vendor folder for dependencies satisfied by the parent directories.

Like @rkulla said, we tend to use existing go tools in Go Report Card. If something like this already exists, maybe we can use it. If not, this could be a chance for someone to create a new tool.

**Comment by rkulla** [comment]
One concern I have, that contradicts my opening this ticket, is that some people (including me) like to commit a vendor/ folder with their library because Golang *currently* doesn't support dependency versions; so most of the package managers will flatten it out and/or use whatever versions the application's vendor folder uses, or they'll pull from master based on import paths your library use.

Including vendor still has some advantages because of that. Further advantages are making sure your library works out-of-the-box if the user doesn't vendor their app. So it's still fairly up in the air.  

What I think would be nice to solve this, would be to have a common way of optionally listing what the known-working dependencies are for libraries. Such as a REQUIREMENTS file (since it's unknown how all the different packaging tools will use or ignore vendor.json if it's included.

**Comment by dlsniper** [comment]
I would say that any discussion at this point is counter-productive as there are no specs for how vendoring will look like in 4 months from now. We should revisit this then imho.

**Comment by rkulla** [comment]
@dlsniper Fair enough

**Comment by xavierhardy** [comment]
What about now @dlsniper, @rkulla? We could also check for Go module files. It's not mandatory yet, but might soon be: https://github.com/golang/go/wiki/Modules
