### ISSUE TITLE
"no such fil or directory" errors during go lint checking

### ISSUE THREAD

**Issue by savinov** [gojp/goreportcard#153]
A lot of "no such file or directory" errors are printed to console during linter check analysis (I've printed log messages before and after lint check, so I think the problem in linter checker).

For example, during goreportcard checking itself repository (https://github.com/gojp/goreportcard) a few hundreds of messages like these is prited:

```
open repos/src/github.com/gojp/goreportcard/repos/src/github.com/gojp/goreportcard/vendor/golang.org/x/sys/unix/syscall_linux.go: no such file or directory
open repos/src/github.com/gojp/goreportcard/repos/src/github.com/gojp/goreportcard/vendor/golang.org/x/sys/unix/syscall_linux_amd64.go: no such file or directory
open repos/src/github.com/gojp/goreportcard/repos/src/github.com/gojp/goreportcard/vendor/golang.org/x/sys/unix/syscall_unix.go: no such file or directory
```

It seems that go linter checker fails, because I have much more linter warnings when I check my sources with metalinter directly than Go Report Card results prints

**Comment by shawnps** [comment]
@savinov I'm not seeing these errors, are you running GRC locally?

**Comment by savinov** [comment]
Yes, I am running latest github version of GRC locally.
Ubuntu Linux 12.04.5, Go version is 1.6.3, gometalinter is latest from the github (but, as I said before, gometalinter works without errors).

**Comment by cloudaice** [comment]
@savinov Are you solve this problem ?

**Comment by savinov** [comment]
No, I just have found this problem and opened the issue.
