### ISSUE TITLE
Exclude testdata directories

### ISSUE THREAD

**Issue by bradleyfalzon** [gojp/goreportcard#156]
The `golint` check is currently reporting issues for `testdata` directories. See https://goreportcard.com/report/github.com/bradleyfalzon/apicompat

However, `testdata` is often contains purposefully invalid code, and should generally be ignored, at least for lint checks. `golint` already ignores this directory (https://github.com/golang/lint/blob/8f348af5e29faa4262efdc14302797f23774e477/golint/import.go#L208 and so does the go tool https://golang.org/cmd/go/#hdr-Description_of_package_lists) and I think goreportcard should to (at least for the lint checks, but perhaps others too).

If agreed and scope can be determined (all tests or lint only), I can investigate further (hints appreciated) and provide PR for review.

**Comment by bradleyfalzon** [comment]
I can't seem to reproduce this in dev, using a fresh GOPATH (via docker):

```bash
docker run -it --rm -p 8000:8000 golang:1.7 bash
go get -u github.com/gojp/goreportcard
cd $GOPATH/src/github.com/gojp/goreportcard
make install
make start-dev
```

After checking http://192.168.1.12:8000/report/github.com/bradleyfalzon/apicompat, golint scores 100% - this is expected behaviour, but production shows 71% and shows the warnings in testdata directories. See 

I've tried a few different things, and from what I can see, golint should've been ignoring this since supporting recursive paths, so I'm not sure why production would be any different (I also checked autocomplete/138-cmd branches and they both report 100% for golint tests).

Any thoughts why production scores golint 71% but development scores golint 100%?

**Comment by bradleyfalzon** [comment]
OK, seems production maybe running an older version of gometalinter before https://github.com/alecthomas/gometalinter/commit/dcc27da2ed95dee794fa7d979d8e3b9b842bbb41

The above change fixes the issue for gometalinter (which is why I couldn't reproduce on dev), but this would still occur for other checks not using gometalinter, so I'll still send through a PR.

**Comment by shawnps** [comment]
Sorry. Using GitHub on mobile on a train :) 

Production could very well be out of date re: gometalinter, I'll update it as soon as I can. Thanks!

**Comment by shawnps** [comment]
@bradleyfalzon just updated gometalinter and all linters on production

**Comment by bradleyfalzon** [comment]
thanks @shawnps I can see the lints are now 100% as expected.
