### ISSUE TITLE
Ignore vendor package for golint

### ISSUE THREAD

**Issue by aanm** [gojp/goreportcard#158]
Is it possible to ignore the vendor package for the golint report?
https://goreportcard.com/report/github.com/gojp/goreportcard#golint

**Comment by lpabon** [comment]
Please.  I'm getting an F in mine due to scanning of vendor directory.

https://goreportcard.com/report/github.com/heketi/heketi

**Comment by shawnps** [comment]
I think this is a regression caused by updating golint or gometalinter on the server, because `vendor` is skipped on my local dev setup. I'm investigating but might not be able to fix for a couple of days as I'm on vacation now.

**Comment by shawnps** [comment]
Yeah, calling gometalinter directly on the server shows tons of files in the `vendor` folder even though I included `--skip=vendor`

**Comment by shawnps** [comment]
Okay there's a `--vendor` flag, I'll add that and it should skip vendor.

**Comment by shawnps** [comment]
@aanm @lpabon please try again

**Comment by aanm** [comment]
@shawnps Fixed, thanks!

**Comment by lpabon** [comment]
@shawnps Awesome! Thanks.
