### ISSUE TITLE
Badge says error yet report pages says a+

### ISSUE THREAD

**Issue by stevenh** [gojp/goreportcard#164]
This is the first time we've used goreportcard, so we may have done something wrong, but the badge is reporting error where as the report says A+

Our repo is: https://github.com/multiplay/go-slack

In our README.md we have
```markdown
[![Go Report Card](https://goreportcard.com/badge/github.com/multiplay/go-slack)](https://goreportcard.com/report/github.com/multiplay/go-slack)
```
Did we do something wrong or is this a bug / caching issue?

**Comment by hermanschaaf** [comment]
Hi @stevenh, sorry to hear you are experiencing issues, but I think you are right that this is likely a caching issue, since it looks fine to me:

![screenshot from 2016-10-31 19 22 34](https://cloud.githubusercontent.com/assets/1121616/19852641/6d07ee8e-9f9f-11e6-860f-5d581e2e86f0.png)

**Comment by stevenh** [comment]
Thanks @hermanschaaf closing :)

**Comment by suzaku** [comment]
I just run into the same issue for https://github.com/juicedata/juicefs, and it doesn't seem to be a cache issue because I see the same "error" state in different browsers.
