### ISSUE TITLE
Score not updated after repo is updated

### ISSUE THREAD

**Issue by Carpetsmoker** [gojp/goreportcard#165]
https://goreportcard.com/report/arp242.net/sconfig seems "stuck" and doesn't update after changes to the repository.

https://goreportcard.com/report/github.com/Carpetsmoker/sconfig (which is the same repo) does work though...

I'll just use the second link for the badge pr0n, but looks like a bug somewhere?

**Comment by shawnps** [comment]
@Carpetsmoker could you try again? This was probably because the server ran out of storage. I need to write a cron that will clean stuff up.

**Comment by Carpetsmoker** [comment]
Seems to work, thanks :+1:
