### ISSUE TITLE
Licence file .txt, issue with extension

### ISSUE THREAD

**Issue by wjdp** [gojp/goreportcard#167]
Hiya, I note #80 exists however this doesn't seem to be resolved. 

![image](https://cloud.githubusercontent.com/assets/1690934/20243747/885a6614-a95c-11e6-8e06-97cf3218439b.png)

See https://goreportcard.com/report/github.com/wjdp/htmltest, licence exists here: https://github.com/wjdp/htmltest/blob/master/LICENCE.txt.

**Comment by wjdp** [comment]
Just noted https://github.com/gojp/goreportcard/blob/master/check/license.go#L26. Seems the spelling is in there, perhaps it's the extension?

**Comment by shawnps** [comment]
@wjdp it looks okay to me after refreshing - maybe the cache was out of date:

![screen shot 2016-11-14 at 1 17 37 pm](https://cloud.githubusercontent.com/assets/80111/20253195/c668d8d0-aa6c-11e6-91d1-2e47d2b7a38e.png)

all good?

**Comment by wjdp** [comment]
I tried removing the .txt extension which is a workaround for this issue. Ended up leaving it like that, however the issue still remains. The tool doesn't recognise a licence file with a .txt extension.

**Comment by shawnps** [comment]
@wjdp okay, let me try to reproduce locally. Thanks

**Comment by shawnps** [comment]
@wjdp I threw a `LICENCE.txt` in here and wrote a test, seems to work:

https://github.com/gojp/goreportcard/commit/927aa0bf5fb6060f4247e516e1e36be35c5ccd3b

still investigating

**Comment by shawnps** [comment]
@wjdp sorry, I'm not able to reproduce this. I made a test repo here with a `LICENCE.txt` and it still passed the check:

http://github.com/shawnps/grctest

I also don't see anything suspicious in the logs related to your repo.

If you want, you can try renaming the file back to `LICENCE` and we can try again to see what happens. Otherwise I'm going to close this and we can reopen if someone else runs into the isuse.

**Comment by shawnps** [comment]
https://goreportcard.com/report/github.com/shawnps/grctest

**Comment by wjdp** [comment]
Peculiar, thanks for the follow up though! Happy for this to be closed.

**Comment by shawnps** [comment]
@wjdp no worries, please reopen if you see this again
