### ISSUE TITLE
Check branch other than master

### ISSUE THREAD

**Issue by marians** [gojp/goreportcard#168]
I don't see an option to check an arbitrary branch of a git repository. However that would be quite helpful as a quality insurance step _before_ merging a PR into master.

**Comment by onuryilmaz** [comment]
I think this feature could help a lot:
- Listen for Github hooks on PR events
- Run checks and save result on a temporary URL (since it would be clicked from merge checks)
- Write response to PR check (for merge checks)

**Comment by shawnps** [comment]
Going to close this as a duplicate of https://github.com/gojp/goreportcard/issues/96 but I'll carry your comments over. Thanks
