### ISSUE TITLE
misspell not up to date?

### ISSUE THREAD

**Issue by voutasaurus** [gojp/goreportcard#169]
I got this output from goreportcard.com:
```
misspell 66%
Misspell Finds commonly misspelled English words
p/gen/word.go
Line 3: warning: found "smears" a misspelling of "swears" (misspell)
```

smears is a word (https://www.google.com/?q=define:+smears).

I tested locally with the latest misspell and there's no misspelling reported.
```
$ go get -u github.com/client9/misspell/cmd/misspell
$ echo "smears" > text.txt
$ misspell text.txt
```

**Comment by shawnps** [comment]
@voutasaurus thanks. Please check again, should be fixed now.

**Comment by voutasaurus** [comment]
Can confirm, thanks! :)
