### ISSUE TITLE
Integrated goreportcard to Jenkins(It's CI tool)

### ISSUE THREAD

**Issue by penhauer-xiao** [gojp/goreportcard#172]
How to integrated goreportcard to Jenkins(It's CI tool)

**Comment by shawnps** [comment]
@penhauer-xiao I'm familiar with Jenkins, we would probably need a command line tool or something like that. I started a tool here:

https://github.com/gojp/goreportcard/pull/155

I'll try to finish it up at some point and get back to you. Thanks

**Comment by penhauer-xiao** [comment]
@shawnps Time is very long, as if no real progress, and the road map Yeah

**Comment by shawnps** [comment]
@penhauer-xiao this project is open source, feel free to work on it if you need this feature urgently. We look forward to reviewing any pull requests you make.
