### ISSUE TITLE
Does it ever report a score that's not A+?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [gojp/goreportcard#173]
I have seen go vet warnings, go lint warnings, misspells on many repositories

https://goreportcard.com/report/github.com/ahmetalpbalkan/dlog
https://goreportcard.com/report/github.com/rakyll/statik
https://goreportcard.com/report/github.com/pkg/errors
https://goreportcard.com/report/github.com/fatih/color

and yet all of them are A+. That sounds a bit odd to me.

**Comment by hermanschaaf** [comment]
Hi @ahmetalpbalkan,

As many users will report, it is indeed possible to get lower than an A+ :) The relevant score calculation code [is here](https://github.com/gojp/goreportcard/blob/83a52eaab452779130af82d5b6afb064836da639/handlers/checks.go#L151-L170). Different checks have different weights. For example, misspell has 0 weight, go lint only has 0.10 weight, and go vet has .25 weight. These weights are defined in the individual check files. This explains why you could have some misspellings or one or two go vet issues and still get an A+.

Another thing to note, and this will likely change in time, is that the weights are added up and calculated per file, not per lines of code or similar metric. We have a ticket for that here: https://github.com/gojp/goreportcard/issues/98

**Comment by ahmetalpbalkan** [comment]
Understood. It's good if it is in your roadmap, we can close this one. However my 2 cents: I think a library’s score should not be a matter of how good/bad others are.

**Comment by shurcooL** [comment]
> it is indeed possible to get lower than an A+

For reference, here are 2 of my repositories containing bad Go code, getting scores of C and D respectively:

- https://goreportcard.com/report/github.com/shurcooL/Conception-go
- https://goreportcard.com/report/github.com/shurcooL/play

(For some reason the score of C doesn't show up in the top left corner though, but I can see it on the badge.)

**Comment by shawnps** [comment]
Thanks @shurcooL. That is strange about the C not showing up. I wonder if it's related to the cache entry being very old (~2 years apparently)

**Comment by ahmetalpbalkan** [comment]
@shurcooL hehe you got some terrible repos. Jokes aside, thanks for showing me that there are some non-A+. I just refreshed the Conception-go and your score is now A. (so goodbye to that repro I guess?)

**Comment by shurcooL** [comment]
> hehe you got some terrible repos. Jokes aside

Yep, those are the only two. All others are really good Go code. See "with the exception of" [here](https://github.com/shurcooL/SLA#applicability). :)

> so goodbye to that repro I guess?

It seems likely that it was indeed related to the cache entry being very old.

**Comment by shawnps** [comment]
@shurcooL that's pretty cool that you have an SLA for your repos. Nice idea!
