### ISSUE TITLE
new feature: errcheck

### ISSUE THREAD

**Issue by awalterschulze** [gojp/goreportcard#175]
Might be worth adding errcheck https://github.com/kisielk/errcheck to the report card?

**Comment by hermanschaaf** [comment]
We actually had errcheck at first, but it was too slow for many repos (often taking more than 1 minute to finish), leading to incomplete results. So errcheck is unabled until such issues can be resolved: https://github.com/gojp/goreportcard/blob/a16b0104fa367218ab1cb8faa0ad175eb81a5ce2/handlers/checks.go#L120

**Comment by awalterschulze** [comment]
Fair enough :)
