### ISSUE TITLE
New repo: github.com/mdlayher/vsock: could not download the repository

### ISSUE THREAD

**Issue by mdlayher** [gojp/goreportcard#178]
Hi all, I love Go report card and use it with all my projects.

Just created a new repository and any attempt to retrieve the report card results in an error.

https://goreportcard.com/report/github.com/mdlayher/vsock
> There was an error processing your request: Could not download the repository.

Any thoughts?  Thanks again!

**Comment by shawnps** [comment]
Hi @mdlayher, glad you like Go Report Card and thanks for reporting this!

This was caused by the server running out of disk space. Your repo should work now.

Thanks!

**Comment by mdlayher** [comment]
Yep, that fixed it. Thanks so much!

**Comment by krostar** [comment]
Dont know if I should open another issue, but I have the same error with [github.com/krostar/nebulo](https://goreportcard.com/report/github.com/krostar/nebulo)

**Comment by shawnps** [comment]
@krostar I can't `go get` your repo:

```
➜  ~  go get github.com/krostar/nebulo
# github.com/krostar/nebulo/router/httperror
mygo/src/github.com/krostar/nebulo/router/httperror/error_handler.go:12: invalid operation: ! func() bool
mygo/src/github.com/krostar/nebulo/router/httperror/error_handler.go:34: non-bool c.Echo().Debug (type func() bool) used as if condition
```

**Comment by krostar** [comment]
It's curious, I don't have any errors
```
$> mkdir ~/newgopath
$> export GOPATH=~/newgopath
$> go get github.com/krostar/nebulo
$> cd $GOPATH/src/github.com/krostar/nebulo
$> make nebulo
```

**Comment by shawnps** [comment]
@krostar I'm heading out but I can take another look in an hour or so if you don't solve it by then

**Comment by krostar** [comment]
I think you have an old [github.com/labstack/echo](https://github.com/labstack/echo) version because in the master branch [debug is an attribute, not a function](https://github.com/labstack/echo/blob/master/echo.go#L76)

**Comment by krostar** [comment]
@shawnps I used a lot of project with something else than master as the default branch name and I never seen any problems with that.

The error you show me earlier tell us you have an old version of the echo package. Is it the same error on the server running goreportcard?

**Comment by shawnps** [comment]
@krostar can you give me examples of other projects that don't use master as the default branch so I can test?

This is what I see on the server:

```
2017/03/22 07:19:11 Update https://github.com/krostar/nebulo
cd repos/src/github.com/krostar/nebulo
git pull --ff-only
cd repos/src/github.com/krostar/nebulo
git checkout master
# cd repos/src/github.com/krostar/nebulo; git checkout master
error: pathspec 'master' did not match any file(s) known to git.
2017/03/22 07:19:11 Failed to update "https://github.com/krostar/nebulo" (exit status 1), trying again...
2017/03/22 07:19:11 Create https://github.com/krostar/nebulo
cd .
git clone https://github.com/krostar/nebulo repos/src/github.com/krostar/nebulo
cd repos/src/github.com/krostar/nebulo
git checkout master
# cd repos/src/github.com/krostar/nebulo; git checkout master
error: pathspec 'master' did not match any file(s) known to git.
2017/03/22 07:19:13 ERROR: from newChecksResp: could not clone repo: exit status 1
```

You can run a local instance and try to debug as well.

**Comment by shawnps** [comment]
@krostar I realized we're not using `go get` anymore. So I guess the default behavior of the vcs package we're using is to checkout master.

**Comment by krostar** [comment]
OK, do you want me to create a new issue, since it's not the same problem? 

Don't know if it can work in all cases, but what about replacing `git checkout master` with `git checkout HEAD`?

**Comment by shawnps** [comment]
@krostar up to you, I'm fine commenting here as well. If you want to see if you can figure out the issue, this is the library we're using:

https://godoc.org/golang.org/x/tools/go/vcs

and this is where we call it: 

https://github.com/gojp/goreportcard/blob/master/download/download.go
