### ISSUE TITLE
Doc oddity with golint

### ISSUE THREAD

**Issue by mcandre** [gojp/goreportcard#179]
According to the Go Report Card, my code is failing golint:

https://goreportcard.com/report/github.com/mcandre/karp#golint

Am I flubbing the Go documentation syntax somehow on line 3?

**Comment by shawnps** [comment]
@mcandre this seems to have been because the cache was outdated. I noticed the last time this repo had been refreshed on GRC was 2 months ago. I clicked Refresh Now and it looks okay to me. Can you confirm and close if it looks good?
