### ISSUE TITLE
Error when default branch isn't master

### ISSUE THREAD

**Issue by krostar** [gojp/goreportcard#180]
This issue start in #178 because I was thinking it was the same problem.
The beginning of the conversation start [here](https://github.com/gojp/goreportcard/issues/178#issuecomment-288311008)

--

I think I figured out how we can solve this issue:

When you use `root.VCS.Create(fullLocalPath, root.Repo)` you checkout the default branch as defined in the remote origin (you can see the default branch with the `git remote show origin` command), for example with your repository:
```
$> git remote show origin
* remote origin
  ...
  HEAD branch: master
  ...
```
In this example, the master branch is the default branch, but it's not always true.
Once the repository is cloned, the current checkouted branch is the default branch (unless you specify a specific branch to checkout).

When you use `root.VCS.Download(fullLocalPath)`, you pull all changes (and you are still in the same previsouly checkouted branch), you don't need to call `root.VCS.TagSync(fullLocalPath, "")`.
If you still want to call this fonction, you have to pass `"HEAD"` instead of  `""` to stay in the currently checkouted branch and avoid using the default one (which is `master`)

Another solution could be to use the `root.VCS.Tags(fullLocalPath)` function to make sure a branch named `master` exist, but it's unlikely that the second branch in the array is the default one, so I don't know how this array of tags can be useful to find the default one.
```
tags, _ := root.VCS.Tags(fullLocalPath)
fmt.Printf("tag command default:%q\ntag list: %v\n", root.VCS.TagSyncDefault, tags)

# Example with my repo
> tag command default:"checkout master"
> tag list: [HEAD dev 0.1.0 0.1.1 0.1.2]
```

IMO, the easiest solution is to simply remove the `TagSync` call.
@shawnps  What do you think ?
Do you want me to submit a pull request or do you want to do it ?

**Comment by krostar** [comment]
up @shawnps

**Comment by bivas** [comment]
This also affects the behavior of goreportcard.com - repos who have no master branch aren't downloaded for processing.

**Comment by hermanschaaf** [comment]
We'd definitely welcome a pull request if anyone can find a solution that doesn't affect current functionality, which uses master by default. The investigation @krostar did looks great, and I'd be happy to test out a potential fix.

**Comment by fubarhouse** [comment]
I know this doesn't help, but I'd also love a solution here. +1

**Comment by shawnps** [comment]
Should be fixed - I copied what `go get` is doing in https://github.com/gojp/goreportcard/commit/d16ec21ff2895bec4c8a977570d97a6e23e88cd4
