### ISSUE TITLE
Remove fake data

### ISSUE THREAD

**Issue by caarlos0** [gojp/goreportcard#182]
There are those ugly `____HIGH_SCORE` repos showing on the high scores page:

![image](https://cloud.githubusercontent.com/assets/245435/25051911/6aa6e3a4-2125-11e7-8eb2-74024e55d589.png)

The repo don't exist anymore: https://github.com/karolgorecki/______________________________________________H_I_G_H_____S_C_O_R_E

It is obviously a fake repo...

Maybe we can remove it?

**Comment by shawnps** [comment]
@caarlos0 we could remove the entries but someone could just add them back unfortunately. We need a better way of determining what can go into high scores. We might want the repo to have a minimum number of stars for example. Something that makes it easier to distinguish the real repos from the fake ones.

**Comment by shawnps** [comment]
@caarlos0 either way I'll go in and remove them. Maybe people will be nice and not add fake repos before we figure out a long term solution 😄

**Comment by shawnps** [comment]
@caarlos0 they're removed now. We can revisit if this happens again. Thanks!

**Comment by caarlos0** [comment]
Thanks :D

> but someone could just add them back unfortunately.

that's why we can't have nice things :(

---

great project, by the way 🍻
