### ISSUE TITLE
Documentation for gocyclo complexity

### ISSUE THREAD

**Issue by fubarhouse** [gojp/goreportcard#184]
Simply put I'd like it documented somewhere,to show what cyclo complexity level is acceptable by goreportcard.

I can't seem to find that anywhere, though I haven't checked the code yet - just repository readme files...

**Comment by onbjerg** [comment]
For now, here's [the check](https://github.com/gojp/goreportcard/blob/a16b0104fa367218ab1cb8faa0ad175eb81a5ce2/check/gocyclo.go#L21). Seems like anything <15 is acceptable.

**Comment by fubarhouse** [comment]
I can close this if you'd like as you have answered the question.
But, I still believe it should be better documented.

**Comment by shawnps** [comment]
@fubarhouse it's actually written here, but this sentence seems to not make sense anymore:

`warning: cyclomatic complexity 20 of function CheckHandler() is high (> 15) (gocyclo)`

the `(> 15)` part is where we're trying to say that we warn on cyclomatic complexity > 15. I'll see if I can update the wording to make more sense.

**Comment by shawnps** [comment]
Sorry, when I say "here" I mean this (this is the goreportcard repo as an example):

![screen shot 2017-05-05 at 2 43 01 pm](https://cloud.githubusercontent.com/assets/80111/25734762/2a674cb6-31a1-11e7-88b3-209f217747d0.png)

**Comment by shawnps** [comment]
Hmm, actually I guess that's the direct output from gocyclo and we don't alter it. I'll stick it in the description above the lines.

**Comment by fubarhouse** [comment]
Cool, sorry for being a hassle here :)

**Comment by shawnps** [comment]
@fubarhouse No hassle at all! It's a good point. I just pushed a change, take a look when you have a moment. I added a sentence to the end of the description here:

```
Gocyclo calculates cyclomatic complexities of functions in Go source code. The cyclomatic complexity of a function is calculated according to the following rules: 1 is the base complexity of a function +1 for each 'if', 'for', 'case', '&&' or '||' Go Report Card warns on functions with cyclomatic complexity > 15.
```

You'll have to click the "Refresh now" button to update.

**Comment by fubarhouse** [comment]
Looks great! Should I close this one now?

**Comment by shawnps** [comment]
@fubarhouse sure, thanks!
