### ISSUE TITLE
False positive from go vet

### ISSUE THREAD

**Issue by korthaj** [gojp/goreportcard#187]
The report at

> https://goreportcard.com/report/github.com/yourbasic/radix

gives a false positve that does not show up when i run "go vet" locally (version 1.8.3):

> go_vet75%
> go vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string.
> radix/example_test.go
> Line 8: error: ExampleSortSlice refers to unknown identifier: SortSlice (vet)

**Comment by shawnps** [comment]
@korthaj thanks. This was reported here too: https://github.com/gojp/goreportcard/issues/113

Unfortunately I haven't been able to track down why it's happening. But I'll close this ticket and keep the other open.
