### ISSUE TITLE
Recent and/or popular searches on bottom?

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#19]
We could maybe add some links to recent or popular searches on the bottom of the page

**Comment by client9** [comment]
see https://www.ssllabs.com/ssltest/ for ideas.

**Comment by hermanschaaf** [comment]
First pass of this is online now (it's just a static list for now, having popular searches would require some more work)

**Comment by shurcooL** [comment]
You could also consider a list like on https://gotools.org/. It just lists 10 most recently viewed packages. It's very inexpensive to compute.
