### ISSUE TITLE
"Last refresh: " xxx "seconds ago" on Reportcard is misleading as long as it is not refreshed

### ISSUE THREAD

**Issue by GoLangsam** [gojp/goreportcard#190]
If I look at the page after a while (and e.g. after a couple of commits) a wording such as "Last refresh: " xxx "seconds ago" makes me believe that the results are fresh. But they are not.

I suggest to only use/show the real (date &) time of the generation - nothing like 'ago' if it's not refreshed.

**Comment by hermanschaaf** [comment]
I think "ago" is more human-friendly than an exact time, which will probably (for simplicity) be in UTC and not the user's timezone. But I agree, the user experience could certainly be better here.

One option I would be happy with is to have javascript update the time on the page, so if you keep the page open long enough, it will start showing "1 minute ago", "2 minutes ago", etc.

We have also talked about automatically detecting when a repo is out of date and then refreshing it, which would be even better, but a more complex change.

**Comment by GoLangsam** [comment]
Looking @ [travis](https://travis-ci.org/) I noticed, that

- they also show a non-refreshed `6 minutes ago`
- but also can I see the *real* time as a tooltip! :-)

Rechecking Your site (and implementation) I realize: I have to admit: I missed this **title** thing. :-(

Thus, now I just wonder about how to make the existence of the tooltip-title visual.
( remember having see bloggers using things such as an superscripted star ... ) 

As I happen to be a purist, I do not feel any need for another javasript feature.

Your `report.html` says
```
  <p>Last refresh: <span title={{last_refresh}}>{{humanized_last_refresh}}</span></p>
```
[Their ](https://travis-ci.org/) html looks like so:
```
<div title="September 24, 2017 22:56:00">
	<svg viewBox="0 0 15 15" class="icon">
		<path class="st0" d="M.861.5H14.22v14H.861zm13.252 4.061H1.182"></path>
		<path class="st0" d="M4.639 7.913c.178-.166.475-.359.893-.359.734 0 2.093 1.164-.906 3.906h2.297m1.295-3.905h2.425s-1.4 1.693-1.4 3.906"></path>
	</svg>
	<time datetime="2017-09-24T15:26:32Z" class="label-align">6 minutes ago</time>
</div>
```
Please notice their use of a `<time datetime=`-tag ...

As of now, I wouldn't mind You closing this issue. I'll come back if I have a more decent proposal.
For now, I like to work with @shawnps on #207 first ;-)

**Comment by GoLangsam** [comment]
@hermanschaaf  I just notice: even `github` behaves similar in their (comment header)[https://github.com/gojp/goreportcard/issues/190#issuecomment-332064543]

( And they just use a slightly (IMHO) more readable format. )
