### ISSUE TITLE
Could not download the repository

### ISSUE THREAD

**Issue by arthurwhite** [gojp/goreportcard#191]
Go Report Card [fails](https://goreportcard.com/report/github.com/gowww/client) downloading [github.com/gowww/client](https://github.com/gowww/client):

```
There was an error processing your request: Could not download the repository.
```

Similar issues: #148, #151, #178, #186.

**Comment by shawnps** [comment]
@arthurwhite I deleted our local copy of your repo on the server and it seems to work now. I'll have to check the logs to see what might have caused it.

**Comment by arthurwhite** [comment]
Perfect, thank you!

**Comment by arthurwhite** [comment]
Maybe the problem was that the first Go Report Card check has been requested while the repo was empty.

Because when I created this new repo, I was still writing the *README.md* locally, before the first commit & push. And I made a markdown preview in VS Code... The README containing the badge, a requesting has been sent to your server to get the image. 💣
