### ISSUE TITLE
Line 1: warning: file is not gofmted with -s (gofmt)

### ISSUE THREAD

**Issue by vcaesar** [gojp/goreportcard#193]
I run "gofmt -s x.go" on Mac and Ubuntu is no problem, but goreportcard shows: " Line 1: warning: file is not gofmted with -s (gofmt)".

**Comment by hermanschaaf** [comment]
Hi @vcaesar, can you post a link to the project? There are a couple of possible reasons I can think of off the top of my head:
 - `gofmt -s x.go` only outputs to stdout by default, to change the file itself you need to run `gofmt -s -w x.go > x.go`
 - Go Report Card does not yet support Go 1.9, if you use any of the new constructs

**Comment by vcaesar** [comment]
Okay, thank you.

**Comment by shawnps** [comment]
Hey @vcaesar, we're happy to take a look if you give us an example project to look at.

**Comment by vcaesar** [comment]
Some files in the editor or ide and do not seem to be gofmted, rewrite the file just fine, another project I used the 1.9.
