### ISSUE TITLE
Recognize duplicate repos on high score page

### ISSUE THREAD

**Issue by 200sc** [gojp/goreportcard#196]
We had the project "OakmoundStudio/oak", then changed the organization display name to oakmound, and now both projects are on the high score list next to each other. We're not trying to game the list; it'd be nice if the former of those two was removed, hopefully by the list recognizing two identical repos.

**Comment by shawnps** [comment]
@200sc thanks. I'm working on a tool for managing the high scores list now. Since this is a rare occurrence I or @hermanschaaf will just field these requests manually. Just removed `OakmoundStudio/oak` from the list now.

**Comment by 200sc** [comment]
Thank you! Also for the quick response!

**Comment by shawnps** [comment]
Thanks for reporting 😄
