### ISSUE TITLE
Unique repos count on high scores page seems wrong

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#199]
"Reports generated for 18,830 unique repos so far."

This seems too high to me. Could be a bug.

**Comment by hermanschaaf** [comment]
Goreportcard has had around 60k unique users, so it sounds plausible to
me...

**Comment by shawnps** [comment]
@hermanschaaf yeah I think you're right, the logic looks sound and I tested a few weird cases on my local and everything looked fine. Closing

**Comment by shawnps** [comment]
Typing the repo with a different case on one letter will increase the count unfortunately :(
