### ISSUE TITLE
Badges with stats

### ISSUE THREAD

**Issue by Horgix** [gojp/goreportcard#200]
First, thanks for making this, it is really useful 🙂 

Second, the reason of this issue: I think it would be really nice to be able to have **badges** for separate stats (gofmt, golint, ...) as well as for the global score as it appears on the High Scores page. The target goal being to be able to just have a glande at the badges without having to click on the current goreport badge to see details.

What do you think about it?

**Comment by hermanschaaf** [comment]
I quite like the idea, to be honest. But it would require some code changes and perhaps a more cluttered UI (which is best avoided), and a CI tool like Jenkins or Travis-CI is perhaps a better place for this. If we get a lot of upvotes on this issue I might rethink my stance, but for now I think it's not worth the extra complication.

**Comment by aalmiray** [comment]
It could perhaps be done by passing additional query parameters to the badge URL, that's how Sonarqube does it for different metrics, for example `image:https://sonarcloud.io/api/badges/measure?key=org.codehaus.griffon:griffon&metric=sqale_debt_ratio["Technical Debt", link="https://sonarcloud.io/dashboard?id=org.codehaus.griffon%3Agriffon"]` results in 

[![Technical Debt](https://sonarcloud.io/api/badges/measure?key=org.codehaus.griffon:griffon&metric=sqale_debt_ratio)](https://sonarcloud.io/dashboard?id=org.codehaus.griffon%3Agriffon)
