### ISSUE TITLE
exit code 2 for every result but the license check

### ISSUE THREAD

**Issue by jannisfink** [gojp/goreportcard#201]
When pressing the "Refresh now" button, every score is 0% and the error message `An error occurred while running this test (exit status 2)` is shown. The only report that works is the license check.

Example: https://goreportcard.com/report/github.com/suluvir/server

**Comment by shawnps** [comment]
Hi @jannisfink 

We've been having an issue lately where the CPU and memory spike dramatically on the server, and everything gets slow. Will have to do some more investigation but for now I restarted the service and it seems better.

**Comment by jannisfink** [comment]
👍 looks good. I will close this one
