### ISSUE TITLE
repos folder is included in the go build path

### ISSUE THREAD

**Issue by tariq1890** [gojp/goreportcard#203]
The 'repos' folder which  holds all the code to be statically analyzed are included in the build path when I run

`go build ./...`

Since I have been working with a fork, I have found this getting in the way often when I want to run the build all command. I have renamed the directory as '_repos' since go build automatically ignores directories that have names beginning with an underscore. I propose that this is done in this project as well. I see two long-term benefits

1. It becomes a problem when we clone repos that do not compile properly and this certainly is problematic if we were to compile the goreportcard code.

2. Right now IDEs like Gogland are indexing all the code that is located in the repos folder. This is unnecessary and time-consuming. Since the underscore prefixed names have special meaning in golang, I predict that IDEs will automatically mark such folders as 'excluded'.

@shawnps @hermanschaaf Let me know your thoughts on this? The changes are simple and they have been working fine on my code.

**Comment by shawnps** [comment]
@tariq1890 That sounds fine to me, if you want to make a PR with the code changes I'll merge and then update the server accordingly.

**Comment by tariq1890** [comment]
Created PR #204
