### ISSUE TITLE
license file not found

### ISSUE THREAD

**Issue by attwad** [gojp/goreportcard#212]
Hi, my go report card has a 0% on the presence of a LICENSE file although it definitely has one:

Go report card:
https://goreportcard.com/report/github.com/attwad/cdf-fe#license
My license:
https://github.com/attwad/cdf-fe/blob/master/LICENSE

**Comment by hermanschaaf** [comment]
Hi, thanks for reporting! 

The report page does not refresh automatically on changes, there is a button the left-hand panel (`Refresh now`) that allows you to pull the latest changes and run the checks again. I checked out the page you linked and saw it was last refreshed a month ago; clicking the refresh button made the license show as 100%.

Hope that helps.

**Comment by attwad** [comment]
Awesome! thanks a lot :)

**Comment by xor-gate** [comment]
Thats weird, I just hit the refresh button and it also complaining at 0% for the LICENSE file. I'm sure the master branch (which probably goreportcard only looks at):

Go report card:
https://goreportcard.com/report/github.com/xor-gate/cicd
My License:
https://github.com/xor-gate/cicd/blob/master/LICENSE

**Comment by shawnps** [comment]
@xor-gate Hi, we don't currently check any branches other than master. It looks like your repo's default branch is develop, so I'm quite sure that's what is causing the issue. Not sure if an issue has been created around that problem but I think it would require us to ping GitHub on every request, which may prove infeasible.

**Comment by xor-gate** [comment]
That explains a lot, you are right. When adhere to Gitflow style there are multiple branches, and I did set the default "view" to develop but master should always be at first sight. I will switch to master then. Thanks for your response.

**Comment by xor-gate** [comment]
I have changed the default to the master branch, still no luck. Not sure what causes the problem.

**Comment by shawnps** [comment]
Hi @xor-gate yeah I think once we clone the repo with the wrong branch, we don't have any logic to fix it when the user updates their default branch to master. Take another look, it should be fixed now after I removed the old repo on our server.

**Comment by xor-gate** [comment]
Yeah it seems to work now.
