### ISSUE TITLE
vanity import paths seem to be skipping boltdb cache and going straight to git

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#214]
Whenever I put a vanity import URL in, it's never found in boltdb and automatically does a git pull. This is expensive

**Comment by hermanschaaf** [comment]
@shawnps I tested this locally and it doesn't seem to be the case, are you sure? Or do you mean that it will get pulled once for the vanity import, and pulled again if you put it in the github url, and saved under a different name?

**Comment by shawnps** [comment]
@hermanschaaf you're right, I just tried a vanity URL and this doesn't appear to be the case. Probably was a different issue, maybe related to /badge endpoint never caching. Closing
