### ISSUE TITLE
Update golint

### ISSUE THREAD

**Issue by jaynagpaul** [gojp/goreportcard#217]
My [goreportcard](https://goreportcard.com/report/github.com/socialplanner/instahelper) is displaying a golint warning using the new type aliases in Go 1.9. Updating to the latest version at https://github.com/golang/lint fixed this for me locally.

Thank you for making such a great and useful tool 🙏 !

**Comment by shawnps** [comment]
@jaynagpaul thanks for reporting, should be fixed now. Reopen if something there's still a problem
