### ISSUE TITLE
There was an error processing your request: Could not download the repository.

### ISSUE THREAD

**Issue by bailantaotao** [gojp/goreportcard#220]
Hi, 

Why my library cannot to do goreportcard, the message can refer to title.

repo URLs: github.com/getamis/eth-client

**Comment by shawnps** [comment]
@bailantaotao we currently have a bug where repos on a default branch other than `master` fail. It looks like your default branch is `develop`. You could change the default branch to `master` for an immediate workaround, or wait for someone to fix the bug.

**Comment by shawnps** [comment]
(or of course submit a PR if you can fix it :))

**Comment by shawnps** [comment]
Issue is here: https://github.com/gojp/goreportcard/issues/180 Closing this ticket as duplicate

**Comment by bailantaotao** [comment]
thanks!! :)
