### ISSUE TITLE
Useless error message for gofmt: "strconv.Atoi: parsing " runtime": invalid syntax"

### ISSUE THREAD

**Issue by unsacrificed** [gojp/goreportcard#222]
I receive following error message for my [project](https://goreportcard.com/report/github.com/apaxa-go/helper) (gofmt test):

> An error occurred while running this test (strconv.Atoi: parsing " runtime": invalid syntax)

This message is useless, even source file does not specified. In general I dont know that to fix and where (or may be it is a bug in gorepocard?).

So:

1. Can someone tell me what does this message mean?
2. I suggest to improve error messages.

**Comment by shawnps** [comment]
@unsacrificed looks like we're running out of memory while running `gofmt` on your repo.

**Comment by unsacrificed** [comment]
@shawnps thanks for information. OOM may be because of large files in my project ('''unicodeh/is-*-gen.go''' & '''unicodeh/tables-*-gen.go''') on the one side and large memory consumption by Go's AST on the othe other side.

Can you say how much memory is available? Then I'll decide that to do.

**Comment by shawnps** [comment]
This project seems to update okay now, albeit it still does consume a lot of the server's resources. We simply need a bigger server, which costs money, which we don't have. Going to close this for now
