### ISSUE TITLE
It will download fail if dest repository's default branch is not ‘master’

### ISSUE THREAD

**Issue by vipally** [gojp/goreportcard#223]
It reports 'There was an error processing your request: Could not download the repository when the repository default branch is not ‘master’
 eg: "github.com/vipally/binary"
It fails when "git checkout master" if repository's default branch is not master 
git fail info:
error: pathspec 'master' did not match any file(s) known to git.

**Comment by shawnps** [comment]
This should be fixed in https://github.com/gojp/goreportcard/commit/d16ec21ff2895bec4c8a977570d97a6e23e88cd4
