### ISSUE TITLE
Could not analyze the repository: no .go files found 

### ISSUE THREAD

**Issue by ddrechse** [gojp/goreportcard#230]
Hi,
This is the error I get when running goreportcard on
github.com/oracle/federated-ingress-controller
There was an error processing your request: Could not analyze the repository: no .go files found 

however, if I fork it
github.com/ddrechse/federated-ingress-controller
goreportcard works fine

Any ideas?

Tnx

**Comment by shawnps** [comment]
Hi @ddrechse 

Looking at the logs, I see something went wrong when we tried to clone the repo originally...I'm not sure what caused that issue, but I deleted the repo on our server and retried and it appears to work now. Please reopen if you run into this again.

Thanks!
Shawn

**Comment by ddrechse** [comment]
Hi Shawn
Tnx for the quick response.  There is one more repo that needs cleansing
github.com/oracle/navarkos

Tnx Much

**Comment by shawnps** [comment]
@ddrechse looks like the same issue, I'll have to do some investigation into why it happened. For now I cleared it out and it should work again. Thanks!

**Comment by ddrechse** [comment]
Tnx again :)  Appreciate it
