### ISSUE TITLE
AddError: could not parse if fileName begins with "-"

### ISSUE THREAD

**Issue by rogozhka** [gojp/goreportcard#238]
https://goreportcard.com/report/github.com/rogozhka/tgwrap

I see no forbiddance for naming like "-wrap-command.go" in language spec. Am I wrong?  
BTW it is useful to sort and group files.

**Comment by shawnps** [comment]
@rogozhka This was probably an issue with our code - I don't think we've seen any repos with files that begin with dashes up until now. It looks like you updated your filenames to remove the dashes from the beginning so I'm going to close this. If someone else runs into it we can revisit. Thanks
