### ISSUE TITLE
error processing request

### ISSUE THREAD

**Issue by rameshthoomu** [gojp/goreportcard#239]
Got the below error when I did refresh on the goreportcard of https://goreportcard.com/report/github.com/hyperledger/fabric. Could you help us or give steps to fix this.
```
There was an error processing your request: Could not analyze the repository: could not clone repo: exit status 1 
```

**Comment by shawnps** [comment]
@rameshthoomu this is due to the default branch not being master. Go Report Card has no way of knowing the default branch when pulling down the repository. The same problem would happen if someone tried to `go get` your repo. If you switch the default branch to `master` it should work.

**Comment by shawnps** [comment]
@rameshthoomu it should work now. Feel free to reopen if you still encounter issues

**Comment by rameshthoomu** [comment]
This is working now. Thanks @shawnps for the quick fix
