### ISSUE TITLE
add grind

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#24]
https://github.com/rsc/grind

**Comment by shawnps** [comment]
It's broken right now https://github.com/rsc/grind/issues/9

**Comment by moorereason** [comment]
Not sure if rsc has abandoned grind or not.  I've been using [this fork](https://github.com/jackspirou/grind) for a while.

**Comment by shawnps** [comment]
@moorereason thanks for the heads up, I have seen that fork but I think it was broken for me last time I tried it. I'll try again soon!

**Comment by shawnps** [comment]
Looks like `grind` hasn't been updated in a long time. Going to close this but if someone really wants it they're of course welcome to make a PR or ticket.
