### ISSUE TITLE
Ignore auto-generated files.

### ISSUE THREAD

**Issue by zenhack** [gojp/goreportcard#241]
It would be useful to be able to ignore auto-generated files. As an example, I have a package that has a bunch of files that are the output of capnproto schema. The issues the report card raises are almost entirely in the generated output:

https://goreportcard.com/report/github.com/zenhack/go.sandstorm

Ideally, the tool would just pick up on the auto-generated comment in those files and ignore them.

**Comment by BenLubar** [comment]
Another example: https://goreportcard.com/report/github.com/BenLubar/steamworks

This doesn't report any errors with `gometalinter` locally due to the `// nolint` comment at the start of the generated file.
