### ISSUE TITLE
False positive in go vet.

### ISSUE THREAD

**Issue by muhlemmer** [gojp/goreportcard#247]
Go vet is giving a false positive:

> Line 29: error: possibly passing Go type with embedded pointer to C (vet)

This occurs in this [report card](https://goreportcard.com/report/github.com/muhlemmer/view).

This is an old [bug](https://github.com/golang/go/issues/20655) in Go, fixed in 1.10. Probably the site is running an older version of Go?

Local `go vet .` doesn't return this error. (Running Go 1.10.1)

**Comment by shawnps** [comment]
Hi @muhlemmer, I've updated the Go version on our server to 1.10 and I'm not seeing this issue on your report anymore. Thank you for reporting!
