### ISSUE TITLE
suggest repositories if none specific given

### ISSUE THREAD

**Issue by wadtech** [gojp/goreportcard#25]
Please forgive me if it behaves differently on a desktop, I've only tried mobile.

I tried out goreportcard and naturally used my own account first. I couldn't remember the name of any of my go repos and entering just the username presents an error flash.

If I enter just the username it would be neat to be displayed a list of available repositories to run the report on.

Optionally then repositories with go code (via the languages api call) could be promoted or the set could be filtered to avoid showing ineligible repos.

Thanks

**Comment by hermanschaaf** [comment]
I still like this idea a lot and would merge it if anyone writes this feature. We couldn't do too many github API calls though, so a start may be to just autosuggest names of repos that already have reports generated.
