### ISSUE TITLE
go report error on github

### ISSUE THREAD

**Issue by doraemon0** [gojp/goreportcard#250]
Please have a look:
The README.md of https://github.com/nknorg/nkn
The badge shows error.
The badge could be accessed: https://goreportcard.com/badge/github.com/nknorg/nkn

If this is not an issue, please close it.

**Comment by shawnps** [comment]
Hi @doraemon0, thanks for reporting this.

I'm not sure why this is happening...we set a `Cache-Control` header when serving the badge which should disallow any caching:

https://github.com/gojp/goreportcard/blob/master/handlers/badge.go#L67

But maybe there is some issue on GitHub's end.

**Comment by doraemon0** [comment]
Hi @shawnps , got it, thank you for your help.

**Comment by shawnps** [comment]
@doraemon0 I've written in to GitHub support to ask about your repo specifically. I'll let you know when I hear back from them.
