### ISSUE TITLE
view : invalid link when there is no master branch

### ISSUE THREAD

**Issue by sarathsp06** [gojp/goreportcard#257]
For the following project there is no branch named "master" but the report link assumes the url to have master in it

https://goreportcard.com/report/github.com/chain/txvm

**Comment by sarathsp06** [comment]
Anyone working in this ??

**Comment by sarathsp06** [comment]
Is anyone working on this or should it be closed

**Comment by shawnps** [comment]
@sarathsp06 It looks like GitHub redirects to the default branch when no `master` is found now. I'll close this out but I'll make a note to look into how we might get the default branch rather than assume it's `master`.
