### ISSUE TITLE
There was an error processing your request: Could not analyze the repository: could not clone repo: exit status 128

### ISSUE THREAD

**Issue by fgm** [gojp/goreportcard#258]
On a local install following the instructions on the project page, all repositories I try return this error: "There was an error processing your request: Could not analyze the repository: could not clone repo: exit status 128"

It even fails on github.com/gojp/goreportcard itself.

Looking into _repos, a repository is created from the project repo, but only contains a single commit taken from a merge of the HEAD commit on the default branch and nothing else. Time stamp matches the HEAD commit but the message is different.

**Comment by shawnps** [comment]
@fgm hmm, could you provide some more details about your installation? Which version of Go, on what OS?

**Comment by fgm** [comment]
go version:
go version go1.11.2 darwin/amd64

uname -a
Darwin FGM-GUI15.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_6

git --version
git version 2.17.0

**Comment by shawnps** [comment]
@fgm are you still seeing this issue? I'm not able to reproduce it.

**Comment by fgm** [comment]
Checking.

**Comment by juan88** [comment]
I'm having the same issue here. I cannot advance through the make install part of the installation procedure.

Any ideas on how it is possible to circumvent gometalinter?

Thanks
