### ISSUE TITLE
Drop gocyclo

### ISSUE THREAD

**Issue by networkimprov** [gojp/goreportcard#263]
Cyclomatic complexity analysis encourages break-up of otherwise coherent functions, giving an illusion of reduced complexity, but more likely a reduction in code quality.

And Go's reliance on `if err != nil { return err }` can cause high scores without any actual complexity increase,

**Comment by shawnps** [comment]
@networkimprov Thanks for the ticket. 

I've considered removing gocyclo in the past, but I haven't seen many complaints about it. That + the thumbs down reactions is leading me to close this ticket out for now, but we can always reevaluate if more people start to hate gocyclo :)

**Comment by mostynb** [comment]
Where's the best place to register dislike for cyclomatic complexity analysis? I agree with @networkimprov's comments, plus also the implementation used here (gocyclo) is abandonware.
