### ISSUE TITLE
go report error on github 

### ISSUE THREAD

**Issue by xujiajun** [gojp/goreportcard#273]
hello,
as title said

The badge shows error.

The badge could be accessed: https://goreportcard.com/badge/github.com/xujiajun/nutsdb

The README.md of https://github.com/xujiajun/nutsdb

can someone give me some advise?

**Comment by shawnps** [comment]
Hi @xujiajun, do you still see the error after doing a hard refresh in your browser? I think the issue might be related to GitHub's caching. I see an A+ badge in the README.

**Comment by xujiajun** [comment]
@shawnps , thanks. I  try to  do a hard refresh, its ok now  :)

**Comment by bcvery1** [comment]
I have the same issue, however it is happening in multiple browsers, incognito mode (Chrome) and after clearing the cache.
Badge: https://goreportcard.com/badge/github.com/bcvery1/tilepix
Report: https://goreportcard.com/report/github.com/bcvery1/tilepix
README: https://github.com/bcvery1/tilepix/blob/master/README.md

The repo has been public for a few hours, and I have refreshed the report page

**Comment by shawnps** [comment]
Hi @bcvery1, I'm seeing an A+ badge on your README. Are you seeing the error badge?

**Comment by bcvery1** [comment]
@shawnps Hey, thanks for the speedy reply, yeah, I'm seeing error on the README, doesn't matter where I view it from (freshly installed browser, and mobile browser I've never view github on before, for example)

**Comment by shawnps** [comment]
@bcvery1 I'm inclined to think it's an issue on GitHub's side (maybe their CDN) if I'm seeing an A+ and you're seeing an error. In which case unfortunately there's nothing we can do :( but I'll keep this open in case more people run into it.

**Comment by bcvery1** [comment]
@shawnps yeah, that sounds about right.  The report seems to be working correctly outside of github.

I'll give it the weekend, I'll report back if just needed time! Maybe it made a difference that I added the badge while the repo was still private...?

**Comment by shawnps** [comment]
@bcvery1 Hmm, Go Report Card doesn't support private repos - do you mean you copied another badge and did a search-and-replace on the repo name before you actually ran it through Go Report Card?

I'd also be curious to see what the HTTP response headers look like for the image URL in the README. For example, is the `Cache-Control` header set?

**Comment by bcvery1** [comment]
@shawnps Yeah, although the "search-and-replace" was changing two URLs, so was straight-forward.

Some (maybe) helpful info from that image request:
```
Request URL: https://camo.githubusercontent.com/2bbff7a23554cf81b85bde5e56a6fca0ae90073e/68747470733a2f2f676f7265706f7274636172642e636f6d2f62616467652f6769746875622e636f6d2f626376657279312f74696c65706978
Cache-Control: max-age=86400
```

**Comment by shawnps** [comment]
@bcvery1 that's weird, I see `Cache-Control: no-store, no-cache, must-revalidate`, which is what we set on our backend.

**Comment by shawnps** [comment]
@bcvery1 so according to GitHub's docs if `Cache-Control` is set to `no-cache` but users are still seeing cached images, we're supposed to contact GitHub support. So I'll do that :) I'll keep you posted.

**Comment by shawnps** [comment]
Hi @bcvery1, I got a response from GitHub:

> Thanks for writing in! We were able to purge the URL for you, all should be working fine now. If you have any other questions or need anything else from us, feel free to message us again!

How does it look on your end?

**Comment by bcvery1** [comment]
@shawnps It looks all good now!  Thanks for all your effort!

**Comment by cjkreklow** [comment]
I'm having this issue right now.  According to https://github.com/github/markup/issues/224 you also need a correct Etag, Expires or Last-Modified.  My current Last-Modified shows 2016 even though the report refreshed a few minutes ago.
```
curl -L -I https://goreportcard.com/badge/kreklow.us/go/go-adsb

HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Mon, 10 Jun 2019 11:44:16 GMT
Content-Type: image/svg+xml
Content-Length: 734
Connection: keep-alive
Accept-Ranges: bytes
Cache-Control: no-store, no-cache, must-revalidate
Last-Modified: Wed, 17 Aug 2016 11:41:00 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

**Comment by laishere** [comment]
Clearing the browser cache is also needed
