### ISSUE TITLE
Renamed GitHub repository causes badge rendering issue for new name

### ISSUE THREAD

**Issue by bmuschko** [gojp/goreportcard#277]
I started out with the a new GitHub repository (https://github.com/bmuschko/lets-gopher). Later I renamed the repository to https://github.com/bmuschko/letsgopher (removed the hyphen). GitHub automatically puts a redirect in place from the old name to new name.

Pointing the GoReport card badge to the new repository in my `README.adoc` file renders "GoReportCard error" instead of the rating. I could only fix this by using the badge from the original repository URL.

```
image:https://goreportcard.com/badge/github.com/bmuschko/lets-gopher["Go Report Card", link="https://goreportcard.com/report/github.com/bmuschko/letsgopher"]
```

I am not quite sure where the issue lies. It's either on GitHub or GoReportCard. Would be great if it could be handled appropriately.

**Comment by shawnps** [comment]
@bmuschko I wonder if there was some caching issue at the time you updated the README. I see an A+ badge here:

https://goreportcard.com/badge/github.com/bmuschko/letsgopher

**Comment by bmuschko** [comment]
@shawnps That's wha I thought first. I waited a couple of days and forced a refresh of the page. The badge is only rendered properly now because I pointed it to the original repository (see https://github.com/bmuschko/letsgopher/commit/7aa77b5271a9797ee8ea58421139a31fe649f204).

**Comment by bmuschko** [comment]
Apparently, the same issue occurs when the repository was private first and then was made public (see badge in https://github.com/bmuschko/kubectl-swiftnp).
