### ISSUE TITLE
FYI: goreportcard library style

### ISSUE THREAD

**Issue by robotvert** [gojp/goreportcard#28]
Hi,

Not an issue, just a heads up.
I needed to score projects programmatically so I extracted the relevant parts and made a [package](/robotvert/goreportcard) out of it.
It might be just me needing this but IMHO it'd be nice if the official project split the "web part" and the "scoring part", to separate concerns and avoid such forks.

Cheers!

**Comment by Oppodelldog** [comment]
This would help me to integrate the scorecard for my private project in jenkins.
I would need to run the checks via command line on local filesystem project and then generate the current html and badge for that project.
I'm curious to see if this can be integrated smoothly.

**Comment by shawnps** [comment]
Thanks for this, I'm going to work on finishing up a command line tool here:

https://github.com/gojp/goreportcard/pull/155

which @Oppodelldog you might find useful for your build.
