### ISSUE TITLE
package awslabs/aws-sdk-go hangs during reporting

### ISSUE THREAD

**Issue by robotvert** [gojp/goreportcard#29]
Whether it's locally using the library I extracted (see issue #28) or online using [http://goreportcard.com/report/awslabs/aws-sdk-go](http://goreportcard.com/report/awslabs/aws-sdk-go) it seems this package hangs halfway through.

**Comment by shawnps** [comment]
Works for me on goreportcard, just takes a long time

**Comment by robotvert** [comment]
takes time indeed. it works now, especially after updating to the latest rev.
I had a gateway error yesterday on grc.com but it seems fine now.
