### ISSUE TITLE
goreportcard needs sponsorship

### ISSUE THREAD

**Issue by tomcam** [gojp/goreportcard#30]
I'll do it. Please contact me at tomcampbell@gmail.com or +1 425 260 5292

**Comment by shawnps** [comment]
Hi @tomcam 

Sorry for the late response.

I really appreciate your offer but Digital Ocean has offered to sponsor it, which makes things easier since the server is hosted there.

Thanks again for offering

**Comment by tomcam** [comment]
Love DO! All right, great to hear.
