### ISSUE TITLE
CLI not working without gometalinter

### ISSUE THREAD

**Issue by qdm12** [gojp/goreportcard#301]
Hi there,

I am trying to run `goreportcard-cli` in a CLI but it seems that it relies on `gometalinter` which cannot be `go get` anymore (even older releases) and is deprecated.

I have the following error when running `goreportcard-cli`:

```
019/11/14 18:40:16 ERROR: (golint) exec: "gometalinter": executable file not found in $PATH
2019/11/14 18:40:16 ERROR: (go_vet) exec: "gometalinter": executable file not found in $PATH
2019/11/14 18:40:16 ERROR: (gofmt) exec: "gometalinter": executable file not found in $PATH
2019/11/14 18:40:16 ERROR: (gocyclo) exec: "gometalinter": executable file not found in $PATH
2019/11/14 18:40:16 ERROR: (misspell) exec: "gometalinter": executable file not found in $PATH
2019/11/14 18:40:16 ERROR: (ineffassign) exec: "gometalinter": executable file not found in $PATH
Grade: F (0.0%)
Files: 10
Issues: 1
gofmt: 0%
go_vet: 0%
golint: 0%
gocyclo: 0%
ineffassign: 0%
license: 0%

misspell: 0%
```

Is there any solution to this? Thanks!

**Comment by titouanfreville** [comment]
Main issue here is that gometalinter is now deprecated: https://github.com/alecthomas/gometalinter
Else installing it will make it work. But we should not need to install a dependencies on a client :)

**Comment by shellfu** [comment]
https://github.com/gojp/goreportcard/pull/298

This seems to solve it. Any reason why this cannot be merged and solve this issue?

**Comment by shawnps** [comment]
I've pinned the required version of `gometalinter` in `tools/tools.go` which gets installed with `make install`, and updated the installation instructions in the README. We might revisit `gometalinter` in the future but for now this seems to work. Please reopen if the installation instructions still don't work for you.

**Comment by TheDiveO** [comment]
Nope, still doesn't work and things got even more confusing. To start with, the most recent README under the "Installation" section says:

    Assuming you already have a recent version of Go installed, pull down the code with `go get`:

    git clone https://github.com/gojp/goreportcard.git

...so which one gives, `go get` or `git clone`?

Cloning the git repo as instructed, changing into it, and running `make install`, then `go install ./cmd/goreportcard-cli` and finally running goreportcard-cli still gives the error messages about missing gometalinter.
