### ISSUE TITLE
502 on `/report/github.com/minon*`

### ISSUE THREAD

**Issue by minond** [gojp/goreportcard#302]
I noticed that the badges to my projects stopped working (some time ago actually, just getting around to creating this issue...) and I get a 502 when I navigate to my project's pages on goreportcard.com. Other projects are working perfectly fine, so this prompted me to play around with the URL and I ended up noticing that I get a 502 on any URL that matches `/report/github.com/minon` (notice how https://goreportcard.com/report/github.com/mino results in a standard application error but https://goreportcard.com/report/github.com/minon results in a 502 from nginx). This is problematic for me since my username is "minond" -- ha! I ran goreportcard locally and I'm able to successfully generate and view reports for all of my repos, so I'm guessing that the request isn't getting past nginx:

Loading report on https://goreportcard.com/report/github.com/minond/captainslog:

![image](https://user-images.githubusercontent.com/601509/69015773-9d594e80-0954-11ea-8908-3d902f0200fe.png)

Loading report for same repo on instance of goreportcard running locally:

![image](https://user-images.githubusercontent.com/601509/69015775-a6e2b680-0954-11ea-9d30-005d0ddf0abc.png)

Any way, thanks for maintaining goreportcard, I really like this tool.

**Comment by shawnps** [comment]
Hi @minond 

We were having some file corruption issues with boltdb, so we switched to dgraph's badger. But it looks like we're still using boltdb in one place, and the code went down that path and panicked when accessing the boltdb file.

I'll look into removing the last pieces of boltdb, but I'm not sure when I can get to it -- hopefully in the next couple of days.

**Comment by shawnps** [comment]
@minond could you try again? I've tried a couple of your repos and it seems to work now.

**Comment by minond** [comment]
It’s working, thanks for looking into this!
