### ISSUE TITLE
Want better integration with shields.io

### ISSUE THREAD

**Issue by gdamore** [gojp/goreportcard#304]
Shields.io generates beautiful shields, with a lot more flexibility than the go report card.  For example, look at the shields on github.com/nanomsg/mangos -- I was able to style that all quite nicely and compactly.

If goreport offered the JSON endpoint for providing the data to shields.io, then I'd have the same options. 

Also, it would be nice to be able to refer to goreport with a nice SVG logo.  (It has to be optimized for the tiny size of the badge.)

**Comment by shawnps** [comment]
We've recently merged a PR that redirects badge requests to shields.io. Please reopen this issue if that didn't solve your problem.

**Comment by everdrone** [comment]
Doesn't seem to allow to customize the colors and logo.

Is it possible to forward all the query params to shield.io?

Specifically:
- color
- labelColor
- logo
- logoColor
