### ISSUE TITLE
`creater` is seen as mispelling `creature`

### ISSUE THREAD

**Issue by HowJMay** [gojp/goreportcard#308]
```
warning: "creater" is a misspelling of "creature" (misspell)
```
see report: https://goreportcard.com/report/github.com/googleforgames/agones#misspell

**Comment by hermanschaaf** [comment]
So, firstly, this should be reported to the misspel library instead: https://github.com/client9/misspell

But secondly, `creater` is indeed not correctly spelled, it should be `creator`. The suggestion offered by misspell is not good, but the word `creater` is indeed not correct.

**Comment by HowJMay** [comment]
Sorry for my mistakes
