### ISSUE TITLE
Perform security analisys using gosec

### ISSUE THREAD

**Issue by Jacalz** [gojp/goreportcard#312]
It would be great if [gosec](https://github.com/securego/gosec) could be integrated as a means of security checking all repositories that are signed up for the report card. It is a good step towards a more secure go ecosystem.

**Comment by arp242** [comment]
gosec tends to have a lot of false positives though.

**Comment by Jacalz** [comment]
Yes you are right, but gosec allows to turn off various checks. The ones that don’t really produce false positives could be used, like for example unhandled errors and other errors that aren’t very common but really bad.
