### ISSUE TITLE
bad reporting: runtime: out of memory issue on goreportcard.com

### ISSUE THREAD

**Issue by henvic** [gojp/goreportcard#313]
Hi, I'd like to report that I tried to import a new project (~ 45k lines of code; has vendorized dependencies) to goreportcard.com and I'm getting a bad report (F, no useful results):

https://goreportcard.com/report/github.com/henvic/wedeploycli

gofmt fails with

```
An error occurred while running this test (AddError: could not parse "_repos/src/github.com/henvic/wedeploycli/color/template/fatal error: runtime: out of memory:1::warning: file is not gofmted with -s (gofmt)" - strconv.Atoi: parsing " runtime": invalid syntax)
```

and everything else but the license fails with

```
An error occurred while running this test (exit status 2)
```

However, if I run it locally, everything but the license passes (perhaps because it is only getting the .go files?).

**I expected:** everything to pass in both scenarios.

I imagine this has something to do with how the website runs the code (probably container doesn't have enough memory).

By the way, thanks a lot for goreportcard! I've been using it for years!

**Comment by mogaika** [comment]
same for [https://goreportcard.com/report/github.com/mogaika/god_of_war_browser](https://goreportcard.com/report/github.com/mogaika/god_of_war_browser)

**Comment by yucaowang** [comment]
+1
Is this caused by server resource limit?

**Comment by shawnps** [comment]
Yup, we probably ran out of memory. One of these days I'll have enough money to upgrade the server and put alerting in place etc. :) Please check again.

**Comment by yucaowang** [comment]
@shawnps It works! Thanks!

**Comment by jeroenrinzema** [comment]
Hi @shawnps , I am noticing a similar issue when generating a go report for https://goreportcard.com/report/github.com/jexia/maestro

**Comment by DocSavage** [comment]
Had same issue :(
