### ISSUE TITLE
Allow for periods in URL routes.

### ISSUE THREAD

**Issue by jackspirou** [gojp/goreportcard#32]
Github allows for ~~usernames, org names, and~~ repo names to include periods, but currently goreportcard.com does not.  If a period is present in the URL route `goreportcard` throws a 404.

I suggest allowing for periods by updating the `makeHandler` method in the `main.go` file to include them:
`^/%s/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)$` -> `^/%s/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_.]+)$`

This way `goreportcard` will be compatible with the same characters github allows for ~~users/orgs~~ repos.

*** updated ***

**Comment by shurcooL** [comment]
> Github allows for usernames, org names, and repo names to include periods,

Do you have a source for that? It doesn't appear to be that way:

![image](https://cloud.githubusercontent.com/assets/1924134/9429854/458230bc-4993-11e5-8de8-79ce9f07d6ef.png)

At least not for usernames.

Also, I see repo names allow for periods, but with certain exceptions:

![image](https://cloud.githubusercontent.com/assets/1924134/9429860/853ab922-4993-11e5-8aec-577f9848c06a.png)

![image](https://cloud.githubusercontent.com/assets/1924134/9429861/932cee88-4993-11e5-9660-319be39f6041.png)

**Comment by jackspirou** [comment]
No source, just thought both were valid, but good catch on the usernames/org names.  

As for repo names, yes, still I would like to include periods that are valid for repository names since that was the issue I discovered.  The search allows for periods so i'm not sure why the URL routes wouldn't as well.

**Comment by jackspirou** [comment]
Updated pull request #33 to account for the updates above.
