### ISSUE TITLE
OOM when generating a report

### ISSUE THREAD

**Issue by lmorg** [gojp/goreportcard#322]
OOM error when running a report against github.com/lmorg/murex
```
An error occurred while running this test (AddError: could not parse "_repos/src/github.com/lmorg/murex/fatal error: runtime: out of memory:1::warning: file is not gofmted with -s (gofmt)" - strconv.Atoi: parsing " runtime": invalid syntax)
```
Works fine when I run goreportcard locally.

**Comment by realshuting** [comment]
Came across the same issue, is there any workaround?

**Comment by lmorg** [comment]
@realshuting I think it's a hosting issue. For now I've been running the tools locally and removed the badge from my README. So I've still got the coverage but unfortunately this way I'm not also promoting the tooling that provided the coverage.

**Comment by lmorg** [comment]
Closing this issue because the problem seems to be resolved
