### ISSUE TITLE
gofmt does not recognize numeric literals introduced by Go 1.13

### ISSUE THREAD

**Issue by krader1961** [gojp/goreportcard#324]
A project I contribute to requires Go 1.14 and uses the numeric literal syntax introduced in Go 1.13. The hosted Go Report Card for the [project](https://goreportcard.com/report/github.com/elves/elvish) reports a gofmt error due to the use of the numeric literal `0o777`. This implies that the hosted version of this program is using a Go version older than 1.13. There are other issues noting that this project appears to require the use of dependencies that are no longer current or that don't work with Go 1.14; e.g., the `gometalinter` project. This is an extremely useful resource but if it is no longer able to track new releases of its core dependencies that needs to be noted in the documentation. As one of the open issues notes the report cards should at least include the version of each tool, or at least the Go version, in the report card. The required minimum (and maximum where that applies) version of each dependency should also be documented in the README document.

**Comment by shawnps** [comment]
@krader1961 We've upgraded to the latest Go version on the server.

Removing `gometalinter` is a much bigger endeavor that unfortunately we will just have to get to when we can, which is probably not in the immediate future.

**Comment by krader1961** [comment]
Thanks for taking the time to update the Go version. That has eliminated all of the spurious errors for the Elvish shell project. I appreciate that replacing the dependency on gometalinter will take a non-trivial amount of work.  I'll review the open issues to see if that is already tracked. If not I'll open an issue noting the need for someone to tackle that work.
