### ISSUE TITLE
golint used by the hosted goreportcard needs to be updated

### ISSUE THREAD

**Issue by krader1961** [gojp/goreportcard#325]
The resolution to issue #324 fixed the recognition of numeric literals by `gofmt` introduced by Go 1.13. However, I see that the `golint` portion of the report still complains about the numeric literal `0o777` in the same package of the Elvish shell project. From which I can only conclude that the `golint` tool used on the hosted goreportcard service predates Go 1.13. I don't see that warning when running `golint` against the Elvish source on my server since I'm using a `golint` built against Go 1.14.

P.S., `golint` is deprecated. See https://github.com/golang/go/issues/38968. Its use in this project should probably be replaced by `staticcheck`.

**Comment by shawnps** [comment]
@krader1961 I've updated `golint` on our server, please try again and let me know how it goes.

**Comment by krader1961** [comment]
LGTM (looks good to me)

The golint portion of the [goreportcard for the Elvish shell](https://goreportcard.com/report/github.com/elves/elvish) no longer shows a spurious warning for the `0o777` literal.
