### ISSUE TITLE
goreportcard.com is not accessible 

### ISSUE THREAD

**Issue by bobdonat** [gojp/goreportcard#328]
It appears that goreportcard.com is not accessible.   Is this why the go report card badge is not showing up? 

Is there an update when goreportcard.com will be online?

**Comment by creekorful** [comment]
I've been suffering the same issue: my Github action that refresh automatically Go report card is failing because of that.

**Comment by shawnps** [comment]
Hi,

We're experiencing high server load and I had to increase our Digital Ocean droplet size. That does seem to be helping but we're still using a lot of memory.
