### ISSUE TITLE
Please bump ineffassign to not report false positives

### ISSUE THREAD

**Issue by rmohr** [gojp/goreportcard#340]
The ineffassign check seems to be pretty old and contain a bug. We see on https://goreportcard.com/report/github.com/kubevirt/kubevirt#ineffassign false positives, which don't happen with latest code from the ineffassign repo.

**Comment by rmohr** [comment]
Related to https://github.com/gojp/goreportcard/issues/232

**Comment by RainbowMango** [comment]
+1
I see on https://goreportcard.com/report/github.com/karmada-io/karmada false positives too.

cc @shawnps @gojp

**Comment by shawnps** [comment]
We're having memory issues with `ineffassign` on large repos. 

Will try to think of a solution, but we might need to just disable `ineffassign` for large repos while we figure it out.

**Comment by RainbowMango** [comment]
> We're having memory issues with ineffassign on large repos.

What kind of memory issues? Have you reported it to the `ineffassign` community?

**Comment by shawnps** [comment]
> What kind of memory issues?

Running `ineffassign ./...` on the https://goreportcard.com/report/github.com/karmada-io/karmada repo (and probably other large repos) on our server uses basically all of its free memory, to the point where other process can no longer allocate.

> Have you reported it to the ineffassign community?

No, not sure if it's a problem with `ineffassign` or our server.

**Comment by RainbowMango** [comment]
It works fine on my side (with the latest ineffassign):
```
# pwd
/root/go/src/github.com/karmada-io/karmada
-bash-4.2# ineffassign ./...
```

**Comment by RainbowMango** [comment]
Have you updated the `ineffassign`? 
No false positives now:
https://goreportcard.com/report/github.com/karmada-io/karmada

![image](https://user-images.githubusercontent.com/8268873/121667454-e182e580-cadc-11eb-990b-85d94d8ae309.png)

**Comment by TomWright** [comment]
I am still seeing false positives, or at least an issue with the way goreportcard is running the checks: https://github.com/gordonklaus/ineffassign/issues/66

**Comment by TheDiveO** [comment]
another batch of false psoitives here, too: github.com/thediveo/netdb

**Comment by TheDiveO** [comment]
Another problem with the old ineffassign: it doesn't seem to handle build flags and thus seem to ignore parts of the sources.

**Comment by shawnps** [comment]
We updated `ineffassign` last month and after testing some of the repos mentioned in this ticket I don't see any false positives. Going to close this but feel free to reopen if anyone is still seeing this issue.
