### ISSUE TITLE
Status 128 when trying to fetch report

### ISSUE THREAD

**Issue by peake100** [gojp/goreportcard#343]
Hello!

I'm getting an error message while trying to generate by report card:

Affected Repo: http://github.com/opencinemac/vtc-go

Error message:

```
There was an error processing your request: Could not analyze the repository: could not clone repo: exit status 128
```

**Comment by peake100** [comment]
Update: I am now getting a 502 error, same as #344

**Comment by njasm** [comment]
Same error for a repo of mine.

Repo: `github.com/njasm/marionette_client`
Error: `There was an error processing your request: Could not analyze the repository: could not clone repo: exit status 128`

**Comment by fubarhouse** [comment]
A personal project is now reporting an `F` and I can't review the report.
`github.com/fubarhouse/pygmy-go`.

**Comment by shawnps** [comment]
Hi, we've been having some backend issues. Please try again, the reports for repos mentioned in this ticket should work now. Let me know if there's still issues.

**Comment by fubarhouse** [comment]
> Hi, we've been having some backend issues. Please try again, the reports for repos mentioned in this ticket should work now. Let me know if there's still issues.

That works again, thanks.

**Comment by peake100** [comment]
Works again for me. Thank you!
