### ISSUE TITLE
404 for any of my repos

### ISSUE THREAD

**Issue by WhyNotHugo** [gojp/goreportcard#351]
I'm trying to us `goreportcard` for a few repos, but they all return 404:

git.sr.ht/~whynothugo/autovdirsyncer
git.sr.ht/~whynothugo/systemd-lock-handler

Maybe it's the `~` in the URL which is kind of not-so-common nowadays?

**Comment by WhyNotHugo** [comment]
Oh, #194 seems related.

However, a bunch of other non-github repositories worked fine, I'm not really sure if that issue is actually still valid or not.

**Comment by WhyNotHugo** [comment]
This is still an issue. Processing most of my got repos still doesn't work.

**Comment by WhyNotHugo** [comment]
Thanks, @hermanschaaf! :)

**Comment by hermanschaaf** [comment]
@WhyNotHugo Yeah, this was related to the tilde in the path, fixed [here](https://github.com/gojp/goreportcard/commit/60688a70a66bf85c44b2bafe82bd1d31403d338a). The example URLs in the original issue description work now:
 - [git.sr.ht/~whynothugo/autovdirsyncer](https://goreportcard.com/report/git.sr.ht/~whynothugo/systemd-lock-handler)
 - [git.sr.ht/~whynothugo/systemd-lock-handler](https://goreportcard.com/report/git.sr.ht/~whynothugo/systemd-lock-handler)

Thanks for reporting!
