### ISSUE TITLE
replace gometalinter (which is deprecated)

### ISSUE THREAD

**Issue by georgettica** [gojp/goreportcard#355]
as seen here the tool relies on gometalinter
https://github.com/gojp/goreportcard/blob/bc8ceed159f60e73cbaf0f9208413e48e86537fe/tools/tools.go#L7

but https://github.com/alecthomas/gometalinter is archived and pushing people towards ttps://github.com/golangci/golangci-lint

I do not want to install gometalinter on my machine as there is an alternative which is maintained

is the migration in the roadmap and if not how can I help to make it a reality?

**Comment by georgettica** [comment]
similar to  #349

**Comment by georgettica** [comment]
@shawnps  this is the issue I was discussing

**Comment by shawnps** [comment]
Thanks @georgettica we'll take a look.

**Comment by georgettica** [comment]
I remembered the tool was not using the new versions and had an alternative that did so I forgot I commented on other PR's

**Comment by shawnps** [comment]
FWIW we've pinned a version of gometalinter that does work, but this is something we've been discussing for a while now so I'll chat with @hermanschaaf about it.

**Comment by hrmnjt** [comment]
Was this discussed? current Go Report Card still includes `golint` as a check

**Comment by tagatac** [comment]
Bump
