### ISSUE TITLE
Upgrade to go 1.17 to fix ineffassign issues with new stdlib functions

### ISSUE THREAD

**Issue by dechristopher** [gojp/goreportcard#356]
![image](https://user-images.githubusercontent.com/12652694/132928266-94b65178-7dc5-4062-b79f-f83b23e1f1ab.png)

`time.Time.UnixMilli` was added in go1.17

**Comment by TheDiveO** [comment]
Looks like ineffassign has other hiccups too: for github.com/thediveo/netdb it reports missing identifiers that clearly exist.

**Comment by fly33499** [comment]
I want to upgrade it!!!!! plz!!

**Comment by shawnps** [comment]
@dechristopher @TheDiveO @jimschubert I believe this has been fixed and I don't see ineffassign issues on the repos you posted above. Feel free to reopen if that's not the case.

**Comment by TheDiveO** [comment]
looks good, thank you very much!
