### ISSUE TITLE
Could not analyze the repository

### ISSUE THREAD

**Issue by YYCoder** [gojp/goreportcard#358]
I've tried a couple of times for my project github.com/YYCoder/thrifter, everything works fine when I use the command-line interface, but when I use the web interface, it shows errors as below:

```text
There was an error processing your request: Could not analyze the repository: could not download repo: could not get latest module version from https://proxy.golang.org/github.com/YYCoder/thrifter/@latest: bad request: invalid escaped module path "github.com/YYCoder/thrifter"
```

it says `could not get latest module version`, but I have tried `go get github.com/YYCoder/thrifter@latest`, no error occurs.

here is my project output using the command-line interface, it worked:

![image](https://user-images.githubusercontent.com/22005951/141894026-4d7709ef-7eba-4e33-9a64-08722be0743e.png)

**Comment by shawnps** [comment]
@YYCoder it looks like Go Report Card is unable to fetch the latest module info from proxy.golang.org:

https://proxy.golang.org/github.com/YYCoder/thrifter/@latest

I'm searching around to see why this might be.

**Comment by shawnps** [comment]
@YYCoder it looks like the code the proxy uses for checking module paths expects lowercase:

https://github.com/golang/mod/blob/master/module/module.go#L738

I'll have a fix deployed shortly.

**Comment by YYCoder** [comment]
> @YYCoder it looks like the code the proxy uses for checking module paths expects lowercase:
> 
> https://github.com/golang/mod/blob/master/module/module.go#L738
> 
> Working on a fix

Thanks for your quick reply, it worked after I change my module path to `github.com/yycoder/thrifter`, but it would be better to provide a way that users don't have to deal with.

**Comment by shawnps** [comment]
@YYCoder yup you're right, unfortunately it wasn't as easy to fix as I initially thought. I'll keep working on it, thanks for raising this issue 👍

**Comment by shawnps** [comment]
@YYCoder I believe this is fixed now. Feel free to reopen this issue if you see the problem again.
