### ISSUE TITLE
Reclone project if "git pull" fails

### ISSUE THREAD

**Issue by alkchr** [gojp/goreportcard#36]
Currently, **goreportcard**  clones a repo just once. Every subsequent attempt to update info about a project triggers `git pull`. Is my understanding correct?
```go
	if os.IsNotExist(err) {
		cmd := exec.Command("git", "clone", "--depth", "1", "--single-branch", url, dir)
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("could not run git clone: %v", err)
		}
	} else if err != nil {
		return fmt.Errorf("could not stat dir: %v", err)
	} else {
		cmd := exec.Command("git", "-C", dir, "pull")
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("could not pull repo: %v", err)
		}
	}
```
https://github.com/gojp/goreportcard/blob/6f08ef1939591fb115678eee84771b88379c7484/handlers/checks.go#L80-L92

If so, there is a flaw in this approach:
1. `git pull` will always fail if I rewrite my git history;
2. if I change my GH username (what I've recently done), a person who decides to use my old one will not be able to test his/her projects that have the same names as my projects had.

I think, if `git pull` fails it should remove the old directory and clone the project again instead of just returning an error.

**Comment by shawnps** [comment]
> Every subsequent attempt to update info about a project triggers git pull. Is my understanding correct?

Yup, that's correct

> 1. git pull will always fail if I rewrite my git history;

this has in fact been an issue in the past for one repo and I ended up manually re-cloning it (bad)

> I think, if git pull fails it should remove the old directory and clone the project again instead of just returning an error.

basically sounds fine to me but i wonder if there is a way to force a pull or something like that. will have to investigate

**Comment by shurcooL** [comment]
> basically sounds fine to me but i wonder if there is a way to force a pull or something like that. will have to investigate

I think you could do:

```bash
git fetch
git reset --hard origin/master
```

Or something like that (not necessarily exactly that). The above does not take into consideration if the default branch is not master. It also wouldn't work if the remote changes (if that's a possible situation).

**Comment by alkchr** [comment]
So, the following change is required:
```diff
- cmd := exec.Command("git", "-C", dir, "pull")
+ cmd := exec.Command("git", "-C", dir, "fetch", "origin", "master")
if err := cmd.Run(); err != nil {
- 	return fmt.Errorf("could not pull repo: %v", err)
+ 	return fmt.Errorf("could not fetch master branch: %v", err)
}
+ cmd = exec.Command("git", "-C", dir, "reset", "--hard", "origin/master")
+ if err := cmd.Run(); err != nil {
+ 	return fmt.Errorf("could not reset origin/master: %v", err)
+ }
```
I have tested it with a project with rewritten history, everything works as expected.
