### ISSUE TITLE
Need help, Refresh error in the goreportcard.com, and the github Library is github.com/wenlng/go-captcha

### ISSUE THREAD

**Issue by wenlng** [gojp/goreportcard#360]
Refresh error in the goreportcard.com, and the github Library is github.com/wenlng/go-captcha.
My library needs to refresh the report. When I click the "Refresh Now" button in web page, 

Url: https://goreportcard.com/report/github.com/wenlng/go-captcha
An error response will be reported:
--------------------------------------------
There was an error processing your request: Could not analyze the repository: could not download repo: could not get latest module version from https://proxy.golang.org/"github.com/wenlng/go-captcha"/@latest: bad request: invalid escaped module path "\"github.com/wenlng/go-captcha\"": malformed module path "\"github.com/wenlng/go-captcha\"": invalid char '"' 
--------------------------------------------

request proxy.golang.org/github.com/wenlng/go-captcha/@latest can respond normally.

**Comment by shawnps** [comment]
@wenlng please try removing the quotes from the first line of the go.mod.

**Comment by wenlng** [comment]
> @wenlng please try removing the quotes from the first line of the go.mod.

Thank you

**Comment by wenlng** [comment]
@shawnps Thank you
