### ISSUE TITLE
gocyclo:ignore does not work

### ISSUE THREAD

**Issue by vkuznet** [gojp/goreportcard#361]
Hi,
I found that goreportcard somehow ignores `gocyclo:ignore` which should prevent reporting high scores. When I add comment `//gocyclo:ignore` to high complexity function the goreportcard still shows this function as high complexity even though manually run `gocyclo` correctly skip it. You may have a look at [dbs2go](https://goreportcard.com/report/github.com/vkuznet/dbs2go) repo where I have plenty of such examples. It would be nice if you'll fix the issue and skip reporting if function is properly declared with `//gocyclo:ignore` comment.

**Comment by shawnps** [comment]
@vkuznet I've upgraded `gocyclo` to [`v0.3.1`](https://github.com/fzipp/gocyclo/tree/v0.3.1) so it should work now. Let me know if you still see the issue.
