### ISSUE TITLE
panic & stacktrace when running on the repo itself

### ISSUE THREAD

**Issue by marcelloh** [gojp/goreportcard#365]
goreportcard % goreportcard-cli
2021/12/01 09:17:41 disabling ineffassign on large repo...
2021/12/01 09:17:41 disabling misspell on large repo...
panic: runtime error: index out of range [1] with length 1

goroutine 25 [running]:
github.com/gojp/goreportcard/check.fileURL({0x102735067, 0x1}, {0x14000308000, 0x3f})
	/Users/marcelloh/data/go-tools/goreportcard/check/utils.go:231 +0x990
github.com/gojp/goreportcard/check.getFileSummaryMap(0x1400019dc58, {0x102735067, 0x1})
	/Users/marcelloh/data/go-tools/goreportcard/check/utils.go:307 +0x198
github.com/gojp/goreportcard/check.GoTool({0x102735067, 0x1}, {0x1400042e000, 0x353, 0x400}, {0x1400019dd58, 0x5, 0x5})
	/Users/marcelloh/data/go-tools/goreportcard/check/utils.go:366 +0x468
github.com/gojp/goreportcard/check.GoCyclo.Percentage({{0x102735067, 0x1}, {0x1400042e000, 0x353, 0x400}})
	/Users/marcelloh/data/go-tools/goreportcard/check/gocyclo.go:21 +0xd0
github.com/gojp/goreportcard/check.Run.func1(0x1400005c1e0, {0x1027815e8, 0x1400005e5a0})
	/Users/marcelloh/data/go-tools/goreportcard/check/check.go:70 +0x38
created by github.com/gojp/goreportcard/check.Run
	/Users/marcelloh/data/go-tools/goreportcard/check/check.go:69 +0x4dc

**Comment by shawnps** [comment]
Fixed in https://github.com/gojp/goreportcard/commit/1237c87143f4e8f325bf4f85145a6b3cf6275042
