### ISSUE TITLE
Include minimum score of dependencies.

### ISSUE THREAD

**Issue by egonelbre** [gojp/goreportcard#37]
The quality of dependencies an important point about the quality of the project.

By including the scores of dependencies it makes it visible. It would also encourage collaboration, e.g. i write a package and get a score C because of a dependencies then I'm more motivated to improve that dependency.

There's the question how to aggregate those dependencies. Minimum seems the most appropriate, chain is as weak as its weakest link.

**Comment by shurcooL** [comment]
This is a pretty fantastic idea. It would be essential to have an easy way to see the all dependencies (including indirect ones) and their scores to make improving the score more actionable.

**Comment by shawnps** [comment]
Sounds nice to me. It could maybe be a new section "dependencies" along with the rest of the tools, which lists out the dependencies and their scores.

I'm a bit worried about it getting significantly slower if the score of the dependencies are not currently in the "cache" (we cache stuff in mongo unless the user explicitly updates it with the Update now link)

If either of you has any ideas let me know and I'd be happy to work on it together or review a PR

**Comment by shurcooL** [comment]
> I'm a bit worried about it getting significantly slower if the score of the dependencies are not currently in the "cache" (we cache stuff in mongo unless the user explicitly updates it with the Update now link)

A way to make sure it's never slow is by not showing the score if it's not already in cache. But then either get the user to manually update those dependency package scores and refresh their original package, or spawn a background task to do the above (and tell the user to refresh later).

**Comment by shawnps** [comment]
> A way to make sure it's never slow is by not showing the score if it's not already in cache. But then either get the user to manually update those dependency package scores and refresh their original package, or spawn a background task to do the above (and tell the user to refresh later).

That sounds good to me. 

I'm thinking at first it will be another section along with the rest of the tools. When you click to expand, it'll list each dependency and its score (or no score), and an Update now link per dependency.

Each dependency in the list will have a link to its own score on Go Report Card.

One problem here is that we decided when building Go Report Card that it would only support github URLs as we needed to finish it quickly for the Gopher Gala. Some changes will need to be made in order to support repos hosted by other providers.

**Comment by shawnps** [comment]
For future reference, this apparently will get a list of non stdlib import paths:

`go list -f '{{.Deps}}' | tr "[" " " | tr "]" " " | xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}'`

not sure if there's a better way

**Comment by egonelbre** [comment]
Regarding slowness, I would use the DB as the main source of content and update it as necessary. I.e. When a person opens new package, it opens it as "loading". It creates an empty entry and marks with "needsUpdate" flag, along with the date it was requested and a priority.

There's one or few goroutines that fulfill those request. I.e. Poll the DB for the next update according to time requested and priority. When the thing needs updated it will add it's full list of dependencies to DB, and also adds "needsUpdate" flag. Of course it will update the "lastUpdated" flag. If between the current time and "lastUpdated" time is less than 2min, the update will be ignored unless explicitly requested by user (to break update cycles).

The priority can be used to specify whether a user requested it or it was a dependency update.

When adding dependencies add -1 to priority and set some limit, e.g. If it's below -20 ignore the request. This is to avoid long update cycles.

Now all the updates and dependencies should be nicely handled.

As for the better way, you probably get better and faster results by using the go source parsing packages rather than invoking go list. Basically you limit yourself to only reading imports that way.

**Comment by client9** [comment]
hi guys...

for ignoring standard libraries, i did this  (cut-n-pasted from some other code i wrote)

go list -f '{{  join .Deps "\n"}}' ../... | 


```
func LoadDependencies(dir string, ignores []string) []string {
        uniq := make(map[string]bool)
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
	        val := scanner.Text()
		ok := true
	        parts := strings.Split(val, "/")

		if len(parts) < 3 || strings.Index(val, ".") == -1 {
                        //log.Printf("ignoring standard library %s", val)
	                continue
	        }

                // ignore other stuff here.. golang/x/

                 uniq[val] = true
	}
      // code to return list of stuff...
```

**Comment by client9** [comment]
re:  by using the go source parsing packages rather than invoking go list. 

@egonelbre  -- I took a look at those but i couldn't really find anything very nice.  Any tips here?

**Comment by egonelbre** [comment]
The untested version, currently this takes the full path to the package rather than the package name -- but I suspect, this version is more useful, since it would work better on package with custom folder structures.

```
package main

import (
	"flag"
	"fmt"
	"go/build"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	flag.Parse()
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, flag.Arg(0), nil, parser.ImportsOnly)
	if err != nil {
		panic(err)
	}

	imports := []string{}
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, imp := range file.Imports {
				path, _ := strconv.Unquote(imp.Path.Value)
				i := sort.SearchStrings(imports, path)
				if i >= len(imports) {
					imports = append(imports, path)
				} else if imports[i] != path {
					imports = append(imports[:i], append([]string{path}, imports[i:]...)...)
				}
			}
		}
	}

	for _, imp := range imports {
		fmt.Print(imp)

		local := build.IsLocalImport(imp)
		standard := !local && ExistsInGoRoot(imp)

		if local {
			fmt.Print("\tlocal")
		}
		if standard {
			fmt.Print("\tstd")
		}

		fmt.Println()
	}
}

func ExistsInGoRoot(imp string) bool {
	goroot := os.Getenv("GOROOT")
	dirname := filepath.Join(goroot, "src", filepath.FromSlash(imp))
	_, err := os.Lstat(dirname)
	return !os.IsNotExist(err)
}
```

I also started to think, how good idea is that... I.e. measure this against using `go list`, maybe the performance win isn't that big.
