### ISSUE TITLE
Is the service down?

### ISSUE THREAD

**Issue by altitude** [gojp/goreportcard#371]
It looks like the hosted service goreportcard.com is down - just checking in and using this issue as an opportunity to offer to sponsor the project monthly, if that can help.

**Comment by drpaneas** [comment]
Indeed the service looks down for couple of hours now. Is this a glitch or a insufficient funds issue?

**Comment by shawnps** [comment]
Hello, thanks for opening this issue.

I'm not sure yet why this happened, but we were able to restart the service successfully. I'm going through the logs now.

While more funds would help us scale up (we do have a [Patreon](https://patreon.com/goreportcard)), it doesn't look like we hit any sort of resource limitation.

**Comment by altitude** [comment]
Fantastic, thanks @shawnps!

**Comment by shawnps** [comment]
Looks like we're having some issues again, I'm investigating now.
