### ISSUE TITLE
Bad request: invalid escaped module path 

### ISSUE THREAD

**Issue by Forceu** [gojp/goreportcard#372]
I'm not sure if the problem is on my side, but I am unable to refresh my project and get the following error code:

`There was an error processing your request: Could not analyze the repository: could not download repo: could not get latest module version from https://proxy.golang.org/gokapi/@latest: bad request: invalid escaped module path "gokapi": malformed module path "gokapi": missing dot in first path element`

The project is Gokapi: https://github.com/Forceu/gokapi

**Comment by shawnps** [comment]
Hi @Forceu, could you try changing the first line of your `go.mod` to `github.com/forceu/gokapi`?

**Comment by Forceu** [comment]
Still the same error? Or is the request cached?

**Comment by shawnps** [comment]
@Forceu the Golang module proxy sees the latest version as v1.3.0:

https://proxy.golang.org/github.com/forceu/gokapi/@latest

https://proxy.golang.org/github.com/forceu/gokapi/@v/v1.3.0.mod

If you tag v1.3.1 I think it should work (you do have a 1.3.1 tag but it needs the v prefix)

**Comment by Forceu** [comment]
Ah I did not realise that it needs to be tagged. Has that been changed? Because half a year ago goreportcard would use the latest master

**Comment by shawnps** [comment]
@Forceu yes, we used to use git but we're now downloading modules from the proxy.
