### ISSUE TITLE
goFmt AddError file not found

### ISSUE THREAD

**Issue by spekary** [gojp/goreportcard#376]
Running on github.com/goradd/got

I received the following error:

An error occurred while running this test (AddError: could not parse "_repos/src/github.com/goradd/got@v0.10.4/internal/got/stat parser.go: no such file or directory:1::warning: file is not gofmted with -s (gofmt)" - strconv.Atoi: parsing " no such file or directory": invalid syntax)

It looks like it is adding "stat " in front of the file name? Either way, parser.go exists, and is not that big, <400 lines, so I doubt its an OOM issue.

**Comment by shawnps** [comment]
@spekary that is interesting. I'm not sure why it happened but I did just refresh the data and it seems to be working:

https://goreportcard.com/report/github.com/goradd/got
