### ISSUE TITLE
parsing bug cause Could not analyze the repository 

### ISSUE THREAD

**Issue by illiafox** [gojp/goreportcard#383]
I want to update `github.com/illiafox/mailbase` card, but have error:
```
There was an error processing your request: Could not analyze the repository: could not download repo: could not get latest module version from https://proxy.golang.org/mailbase/@latest: bad request: invalid escaped module path "mailbase": malformed module path "mailbase": missing dot in first path element 
```
Site don't parse my link normally, so it call `https://proxy.golang.org/mailbase/@latest` instead of `https://proxy.golang.org/github.com/illiafox/mailbase/@latest`

**Comment by shawnps** [comment]
Hi, please try changing the module name in `go.mod` to `github.com/illiafox/mailbase`:

https://github.com/illiafox/mailbase/blob/master/go.mod#L1

**Comment by illiafox** [comment]
@shawnps didn't help

**Comment by shawnps** [comment]
@illiafox it may take some time for the Golang proxy to update.

https://proxy.golang.org/github.com/illiafox/mailbase/@latest

You can see it still has the old `go.mod` here:

https://proxy.golang.org/github.com/illiafox/mailbase/@v/v0.0.0-20220326071402-4612c2da4689.mod

**Comment by shawnps** [comment]
@illiafox seems it updated:

https://proxy.golang.org/github.com/illiafox/mailbase/@v/v0.0.0-20220326072947-96a213b5357d.mod

https://goreportcard.com/report/github.com/illiafox/mailbase

**Comment by illiafox** [comment]
yeah, thanks!
