### ISSUE TITLE
Report failing for repo for unknown reasons

### ISSUE THREAD

**Issue by emirpasic** [gojp/goreportcard#384]
Given a couple of tools are failing on the report for [https://goreportcard.com/report/github.com/emirpasic/gods](https://goreportcard.com/report/github.com/emirpasic/gods), I assume it has to do something with the infrastructure, or?

Please let me know if this can be fixed or if I can do something to resolve the issue, thanks!

![image](https://user-images.githubusercontent.com/3115942/163492556-bf99f2ff-676a-4af4-b5d5-add6b6c02a25.png)

**Comment by shawnps** [comment]
@emirpasic the server was out of memory so I restarted it and the report looks okay now. I think we may have a memory leak somewhere, but unfortunately I don't have time to look into it atm.
