### ISSUE TITLE
give points for having a LICENSE/COPYING file

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#40]

**Comment by client9** [comment]
cc @client9

**Comment by client9** [comment]
more points if it's a license that is detectable from https://github.com/ryanuber/go-license

**Comment by client9** [comment]
here's a sample of a repo without a license

http://goreportcard.com/report/robertkrimen/isatty

**Comment by shurcooL** [comment]
Please don't penalize for having license in README rather than a standalone file. I really dislike the pollution of files like AUTHORS, COPYING, CONTRIBUTING.md, README.md, LICENSE, etc. and I don't want to get points taken away from having a neater repo.

Not having a license at all is another story.

**Comment by shawnps** [comment]
@shurcooL that seems to be the GitHub standard (LICENSE) when adding a new repo:

![screen shot 2015-10-14 at 4 11 26 pm](https://cloud.githubusercontent.com/assets/80111/10477079/4b0dd698-728e-11e5-9be3-d1ebb5bf9435.png)

how do you propose finding a license within the README file?

**Comment by shurcooL** [comment]
> how do you propose finding a license within the README file?

It's a harder problem. I proposed not penalizing for not having LICENSE, which is easier.

**Comment by shawnps** [comment]
> I proposed not penalizing for not having LICENSE, which is easier.

Okay, correct me if I'm wrong: bonus points if you have LICENSE, but a repo without LICENSE could still hit 100%

**Comment by mattfarina** [comment]
I noticed it now checks for licenses. I expanded on that a little with pull request #46.

**Comment by mholt** [comment]
Would be nice if it worked for files called LICENSE.txt :sweat_smile:

**Comment by mattfarina** [comment]
@mholt that was merged in a few days ago. If you refresh on a project it should work now.

**Comment by mholt** [comment]
:+1: Bravo - thanks!
