### ISSUE TITLE
show me my repo ...

### ISSUE THREAD

**Issue by ghdwlsgur** [gojp/goreportcard#400]
I searched my github repository (github.com/ghdwlsgur/govpn) on the goreportcard homepage, but I get the following error.

[error]
There was an error processing your request: Could not analyze the repository: could not download repo: could not get latest module version from https://proxy.golang.org/govpn/@latest: bad request: invalid escaped module path "govpn": malformed module path "govpn": missing dot in first path element

Initially the module name was govpn, I changed the module name to github.com/ghdwlsgur/govpn but I keep getting the following error.

Help me!!! 😭😭😭

**Comment by shawnps** [comment]
@ghdwlsgur please try pushing a new tag -- the module name is incorrect in v0.1.2

**Comment by ghdwlsgur** [comment]
Thank you for quick response !! 👍🏻👍🏻👍🏻
I will release a new release and come back.

**Comment by ghdwlsgur** [comment]
https://goreportcard.com/report/github.com/ghdwlsgur/govpn

Oh yeah i'm so feel goooooooooooooood 

solved it !!!! Thank you

**Comment by shawnps** [comment]
@ghdwlsgur no problem, glad I could help 😄
