### ISSUE TITLE
How is scoring done.. perhaps make a bit more strict

### ISSUE THREAD

**Issue by client9** [gojp/goreportcard#41]
I wouldn't call this A+, but maybe I'm too picky.

Anyways .. thanks making such a nice service.

n

http://goreportcard.com/report/ugorji/go

A+    Excellent!
Found 22 issues across 28 files

gocyclo	 53%
gofmt	 85%
golint	 32%
go_vet	82%

**Comment by shawnps** [comment]
This was caused by the grade being calculated based on an overall average, and once I added license since this repo has a LICENSE file the grade got boosted quite a bit. I'm working on making it a weighted average now with less weight going to LICENSE file.

**Comment by shawnps** [comment]
Assigned these weights:

```
license: 10%
gocyclo: 22.5%
gofmt:   22.5%
golint:  22.5%
go vet:  22.5%
```

ugorji/go should have a C now. Will see how this works out and can reopen this if it isn't quite good enough.

**Comment by shawnps** [comment]
I actually think go cyclo and go lint could maybe be weighted a bit less...we'll see

**Comment by shurcooL** [comment]
go vet issues are much, much more severe than lint issues.

**Comment by shawnps** [comment]
@shurcooL yeah that's a good point. I'll reduce golint's weight.
