### ISSUE TITLE
case sensitivity issue on highscores page

### ISSUE THREAD

**Issue by client9** [gojp/goreportcard#45]
good stuff guys.

Found a nit on highscore page:
```
3	golang/crypto	185	86.49
44	Golang/crypto	185	86.49
```

**Comment by hermanschaaf** [comment]
This is still an issue. It could be as simple as lower-casing all go get queries?

![screenshot from 2016-04-29 14 34 21](https://cloud.githubusercontent.com/assets/1121616/14909559/a1320b64-0e17-11e6-9c9c-bb54c5451f1e.png)

**Comment by shawnps** [comment]
@hermanschaaf that could work probably, and we'd also want to remove the duplicates from bolt

**Comment by shawnps** [comment]
We're doing a lowercase string comparison when inserting into high scores now, and if an entry already exists we remove it rather than inserting twice.
