### ISSUE TITLE
Empty error when testing minimaxir/big-list-of-naughty-strings/naughtystrings

### ISSUE THREAD

**Issue by matrixik** [gojp/goreportcard#48]
Hello,

When I try to test https://godoc.org/github.com/minimaxir/big-list-of-naughty-strings/naughtystrings site is showing empty error:
`Oops! There was an error processing your request: {}`

**Comment by shawnps** [comment]
Hi @matrixik 

The app works on the repo-level, so you would pass  `minimaxir/big-list-of-naughty-strings` rather than `minimaxir/big-list-of-naughty-strings/naughtystrings`:

http://goreportcard.com/report/minimaxir/big-list-of-naughty-strings

**Comment by matrixik** [comment]
O, thank you. Maybe it can be returned in error msg?
