### ISSUE TITLE
More informative error messages

### ISSUE THREAD

**Issue by alkchr** [gojp/goreportcard#49]
`Oops! There was an error processing your request` and `500 Internal Server Error` are not really informative. Here is [an example](http://goreportcard.com/report/goaltools/iniflag) for illustration. I have no clue what's wrong with it and I'm not able to reproduce the error locally ([the same](http://goreportcard.com/report/goaltools/INIFlag) repo but uppercased works as expected).

**Comment by shawnps** [comment]
@alkchr try again. You're correct about surfacing the error messages, will look into that later. The problem was on the server and it's been fixed for now.

**Comment by shawnps** [comment]
duplicate of this:

https://github.com/gojp/goreportcard/issues/16

**Comment by alkchr** [comment]
@shawnps Thanks for fixing the issue related to my repo.

**Comment by shawnps** [comment]
@alkchr anytime, thanks for making the issue!
