### ISSUE TITLE
Include any Git repository other than github.com

### ISSUE THREAD

**Issue by onuryilmaz** [gojp/goreportcard#51]
It would be better if we can include any other git repositories.

**Comment by shurcooL** [comment]
Indeed.

Go makes it very easy with these funcs:

- [`golang.org/x/tools/go/vcs.RepoRootForImportPath`](https://godoc.org/golang.org/x/tools/go/vcs#RepoRootForImportPath)
- [`golang.org/x/tools/go/vcs.Cmd.Download`](https://godoc.org/golang.org/x/tools/go/vcs#Cmd.Download)

Websites like godoc.org, gotools.org, gocover.io, etc., already support arbitrary valid (as in, go-gettable) import paths.

**Comment by client9** [comment]
Semi-related 

I frequently attempt to cut-n-paste a package name from a golang source file which fails, i.e.

Try to do this:

```
github.com/client9/misspell
```

But should be

```
client9/misspell
```

:-(

Just removing the hardwired github.com I think will allow other non-github repos to work and make it easier for github.com repos  !!

**Comment by shawnps** [comment]
This ought to work now with the new way we pull repos down (using `go get` rather than `git`):

https://goreportcard.com/report/golang.org/x/crypto/ssh

Someone can reopen if any issues come up.
