### ISSUE TITLE
make the high scores page more configurable

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#55]
Right now a repo will only appear on `/high_scores` if it has > 100 files. That was just a number that I chose arbitrarily. There are probably plenty of great repos that have 1-99 files :) Could probably pass the min number in a query parameter or something.

**Comment by shurcooL** [comment]
Why even have a minimum of .go files requirement? Is it because otherwise there are too many tiny repos with perfect scores, making results not interesting?

**Comment by hermanschaaf** [comment]
@shurcooL Yes, that was the original reason. A better measure might be total line count - but I think we don't store that in the database right now. Maybe we should?

**Comment by shawnps** [comment]
This doesn't seem super important to many users so I'm going to close it out. If someone really wants it they can make a PR or new issue.
