### ISSUE TITLE
misspell update / re-org

### ISSUE THREAD

**Issue by client9** [gojp/goreportcard#56]
Thanks to goreportcard a bunch of false positives have been fixed.  

More importantly

* Long blocks of text with no whitespace are ignored.  This eliminates false positives in urls and big chunks of base64 text that sometimes are in source files.
* For Golang files only comments are checked for spelling (for now).  You can change this behavior to check everything with `-source=text`.  I may expand this to include raw strings but only if it behaves nicely.
* Big API update... to make sure you install with 

```bash
go get -u github.com/client9/misspell/cmd/misspell
```

(maybe do this first to make double sure)

```bash
rm `which misspell`
```

onward!

**Comment by shawnps** [comment]
Thanks for the fixes @client9, I updated `misspell` on goreportcard.com
