### ISSUE TITLE
make last refresh date more obvious when it's old

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#57]
some users may not realize that clicking Test Now pulls data from a cache unless they explicitly click Update now. maybe the last refresh text could be colored red if it's quite old or something

**Comment by hermanschaaf** [comment]
it would also be nice to have the date be relative, like "4 days ago", or "1 year ago", instead of the timestamp we have now

**Comment by shawnps** [comment]
> it would also be nice to have the date be relative, like "4 days ago", or "1 year ago", instead of the timestamp we have now

this is done now
