### ISSUE TITLE
add TODO count?

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#62]
This doesn't need to have a score impact, and maybe it's controversial, but I personally like to see no TODOs so it might be interesting to count them.

**Comment by hermanschaaf** [comment]
I agree that this would be useful. We can show the TODO count (and list out the TODO locations like we do for errors / warnings), but yes, I would not have it affect the score. The TODOs could be for new features, discussions, etc, which have no impact on the current quality of the code.

**Comment by atakanyenel** [comment]
I started learning Golang (I have experience in web dev) and I want to work on this issue to better understand how go works. Todos do not intervene with the grade reports and looks easier than other issues.

As you are not using many external libraries, I will add my regex logic as a file in the `check` folder and add the `todofinder` function to the overall process. Also add the corresponding html, and 100% statement coverage for the function.
