### ISSUE TITLE
https

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#64]

**Comment by hermanschaaf** [comment]
https://letsencrypt.org/

**Comment by hermanschaaf** [comment]
:+1:

**Comment by hermanschaaf** [comment]
![screen shot 2016-02-04 at 21 48 13](https://cloud.githubusercontent.com/assets/1121616/12816727/056f223c-cb89-11e5-85ad-72e5305b2e6a.png)

**Comment by shawnps** [comment]
wow. let's encrypt is cool.

**Comment by shawnps** [comment]
i'm gonna call this done, amazingly. can reopen if any issues occur but we should have let's encrypt working with auto renewal now. that was fun
