### ISSUE TITLE
idea: hit github to see if repo is up to date or not, hide Update Now if it is

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#66]
@hermanschaaf's idea, we could hide the Update Now link for a repo if we know we're up to date with the upstream...that way for a large repo for example it wouldn't get updated and run through all the checks (and take a long time).

**Comment by hermanschaaf** [comment]
We could even automatically update the repo if we see there are changes since the last time we updated it. I think the extra time some users will have to wait will be an acceptable trade-off for not ever having to manually click the "Update Now" link

**Comment by shawnps** [comment]
@hermanschaaf ah, that's a good idea :+1:

**Comment by shawnps** [comment]
Someone requested this in #goreportcard on the Gophers Slack, but I'm not sure we necessarily want to hit GitHub for this info. One idea that we came up with is to go through the repos in the cache, check for smaller repos (maybe < 50 .go files or something), and update those periodically.
