### ISSUE TITLE
Github readme badges

### ISSUE THREAD

**Issue by hermanschaaf** [gojp/goreportcard#7]
...a request we have received many times, and something I personally want too :smiley_cat:

**Comment by hermanschaaf** [comment]
It works!

![screenshot from 2015-02-08 11 24 56](https://cloud.githubusercontent.com/assets/1121616/6094918/251c7024-af85-11e4-9919-e29d31d18c27.png)

... but Github is aggressively caching the image on their CDN. We need to send the `Cache-Control: no-cache` header to avoid that, and I'm not sure if we can do it with the current hacky way I'm redirecting to the image location on shields.io. Will need to fix this before adding links to the badge on the site :cat2:

**Comment by gdamore** [comment]
Yes please!  Maybe what should happen is that shields.io should present an ETag.  If that were done, then you wouldn't have to disable caching.  Put another way, I think this needs to be solved by shields.io, not goreportcard.

**Comment by shawnps** [comment]
This might already be happening, so maybe everything is fine..? https://github.com/badges/shields/issues/221 will have to test it a bit

**Comment by client9** [comment]
It seems to work

**Comment by client9** [comment]
But it is not advertised nor clear how to do it.  I just copied what I found in 
https://raw.githubusercontent.com/gojp/goreportcard/master/README.md

**Comment by shawnps** [comment]
well, i'm showing it on the page, but that requires people to copy the img address and do some manual work to get it into their readme... should be able to make it nicer i'm just bad at JS

**Comment by shawnps** [comment]
seems that you also need to hard-refresh to get the newest badge if the repo's grade changes

**Comment by hermanschaaf** [comment]
Yes, the reason we didn't advertise it is that you need to hard-refresh for it to update, because it's getting cached. Right now, if memory serves, we are returning a redirect to the image hosted on shields.io, and that is what gets cached. If we want to fix this properly, I think we might need to work with shields.io, or add a no-cache header to the images we serve ourselves.

**Comment by hermanschaaf** [comment]
Actually, is a hard-refresh always enough? I thought it was github's CDN caching the image, not the browser

**Comment by shawnps** [comment]
@hermanschaaf ah sorry to be more specific, I meant I had to hard refresh the Go Report Card page that I'm displaying the badge on, not the README that someone might put it in

**Comment by hermanschaaf** [comment]
I'm going to close this issue for now. The badges do seem to update if you force refresh once or twice. So... until someone complains, let's close this one and focus on other things.

**Comment by miniwark** [comment]
As the badges use shields.io, if possible, if would be nice to allow the use of shield.io ?style parameters (and maybe other too like ?label and ?maxAge). I miss the possibility to flat square this only badge on my project.

**Comment by hermanschaaf** [comment]
@miniwark We just added a feature that allows you to style the badge (thanks @Tomohiro!)

You can do it simply by adding `?style=[style name]` to the existing URL in your readme. The options for style names are the same as on shields.io, i.e.:

 - `?style=plastic`
 - `?style=flat`
 - `?style=flat-square`
 - `?style=social`

**Comment by miniwark** [comment]
@hermanschaaf Thanks! I confirm than this is working.

**Comment by chmike** [comment]
The badge is unfortunately not updated on github. It works well with travis and goverall badges. 
github displays a B, while I now have an A+. This is frustrating. 

Thank you for the package and service. It's a great service to enhance code quality. I wish I could see my numeric score.

**Comment by shawnps** [comment]
@chmike would you mind posting a specific repo so we can take a look? Thanks

**Comment by hermanschaaf** [comment]
Hi @chmike, thanks for the feedback! This is probably due to image caching on the part of either Github, or your browser. A browser hard refresh might fix it. You didn't specify which repository you are talking about, but if it's securecookie, it shows as an A+ to me:

<img width="1005" alt="screenshot 2017-09-23 18 05 47" src="https://user-images.githubusercontent.com/1121616/30775369-031c7336-a08a-11e7-8969-4d0d8bcfe0f2.png">

**Comment by chmike** [comment]
Yes! That is the repository. Thank you very much.  How come that I only see a B ? I tried connecting from another computer (same network) so the browser cache can't be in play. I also tried a hard refresh with shift reload and ctrl-F5 (windows). I tested with my phone, (fresh connection & different provider) and I also see the B label. It looks like a github issue.

**Comment by hermanschaaf** [comment]
Yeah, Github does some pretty aggressive caching of the images, unfortunately. If you look at the image source on the readme, you'll see that it actually links to `camo.githubusercontent.com`, not `goreportcard.com`. We set a cache-control header (https://github.com/gojp/goreportcard/blob/master/handlers/badge.go#L68) to tell Github not to cache the image, but looks like they (or, potentially, a proxy in between you and them) are not respecting it.

**Comment by chmike** [comment]
I could see the A+ after two hours delay. Good to know if some raise up the problem again. Some cache in the path needed to be refreshed. The cache save your servers from many requests and reduce display latency. So its OK. Thank you for the fast response and for keeping the service running.

**Comment by fubarhouse** [comment]
Is there any intention right now to add the "for-the-badge" style - because it clearly isn't supported...

**Comment by hewiefreeman** [comment]
This might be an old topic, but I'm having the same issue: Github's caching is preventing my badge from updating even with a hard refresh.

Since you're already using query strings for styling the image and headers just don't get the job done, you could add another query string to the Image URL and Markdown templates (on the report cards). It's effective enough to just get the ID of the latest commit and make the dynamic URLs like:

 `https://goreportcard.com/report/github.com/username/ProjectName?v=lastCommitID`

Or with a style:

`https://goreportcard.com/report/github.com/username/ProjectName?v=00ec17d&style=plastic`

Shouldn't this be a built-in feature since the badges are used in and viewed from Github a lot?
