### ISSUE TITLE
PushState happens twice when report is generated

### ISSUE THREAD

**Issue by winhowes** [gojp/goreportcard#70]
It seems like `history.PushState` fires twice - I have to go back 2 pages to get to the search page

**Comment by hermanschaaf** [comment]
Thanks for reporting! I noticed this too, it is quite annoying. PRs welcome :bow:

**Comment by hermanschaaf** [comment]
This is fixed in https://github.com/gojp/goreportcard/commit/d3856ba793f0c3ad582d344d969392b9b19f39b7 - to be deployed live soon...

**Comment by winhowes** [comment]
Nice

**Comment by hermanschaaf** [comment]
Okay it's more or less fixed on live now. It's a little hacky - we should probably stop using push state entirely and just redirect the page, and then show a loading bar if necessary. Would make the application simpler and I don't think anyone will really even notice.
