### ISSUE TITLE
Request: Search from report card page

### ISSUE THREAD

**Issue by winhowes** [gojp/goreportcard#71]
Once I've searched one report - there's no easy way to search another report without going back. It'd be great if there was still a search bar at the top.

Bonus - the search bar autocompletes suggestions :D

**Comment by shawnps** [comment]
+1

**Comment by hermanschaaf** [comment]
+1 this would be a nice addition

Autocomplete is actually something Bolt allows us to do quite easily, as it supports prefix scans: https://github.com/boltdb/bolt#prefix-scans . This assumes we only autocomplete repos that have been searched before, but that seems reasonable for now.

**Comment by shawnps** [comment]
> This assumes we only autocomplete repos that have been searched before, but that seems reasonable for now.

@hermanschaaf I think this would be totally fine for now. We have data on over 5,000 repos including many of the most popular Golang repos, so there'd be a fair bit of stuff to autocomplete I think.

**Comment by winhowes** [comment]
Yeah the auto-complete idea was just to make it easier doing duplicate searches (to for instance, see how their repo is improving).

The bigger thing though would being able to search again from the report without having to go back

**Comment by hermanschaaf** [comment]
Added the search bar, but no autocomplete yet. Thanks for the suggestion! :+1:
