### ISSUE TITLE
hitting "Refresh now" causes result list to double in size

### ISSUE THREAD

**Issue by shawnps** [gojp/goreportcard#75]
reported by @wickett

https://goreportcard.com/report/github.com/gauntlt/gauntlt-go

hit Refresh now, and everything will show up twice in the list

**Comment by hermanschaaf** [comment]
Will be fixed once https://github.com/gojp/goreportcard/commit/d3856ba793f0c3ad582d344d969392b9b19f39b7 is deployed

**Comment by hermanschaaf** [comment]
Deployed and confirmed fixed, but you might need to do a hard-refresh to get the fix if you already loaded that page before.
