### ISSUE TITLE
Infinite Redirect Loop

### ISSUE THREAD

**Issue by 256dpi** [gojp/goreportcard#79]
I just experienced several infinite redirect loops when going on the website.
Any others experience the same issue?

Btw: Thanks for the great tool!

**Comment by hermanschaaf** [comment]
Oh, thanks for reporting! Can you tell me which URL you visited? I haven't experienced this, but will fix ASAP

**Comment by 256dpi** [comment]
The following URL causes the problem:
https://goreportcard.com/report/github.com/gomqtt/client

But it also happens on the root.

Strange is that the server response with a "OK" rather than a "Moved Permanently" or similar...

**Comment by 256dpi** [comment]
Update: It looks like the problem is limited to Safari.

**Comment by 256dpi** [comment]
I guest it is related to that issue: http://stackoverflow.com/questions/28441025/ignore-safaris-initial-page-load-popstate

**Comment by hermanschaaf** [comment]
Thanks! It's nice to work on a project where the users debug their own bug reports ;)

So I decided to just get rid of pushState, it was causing more trouble than I feel it's worth. I tried loading it on mobile safari at least, seems fine now. Please let me know if it's not the case!

PS Side-note: now I understand why I always get an infinite redirect loop when I visited gmail from mobile Safari. Used to at least, not sure if they've finally fixed it.

**Comment by 256dpi** [comment]
All works fine now! Thanks :+1:
