### ISSUE TITLE
Handle `COPYING` files and `License` (different case and extensions)

### ISSUE THREAD

**Issue by hermanschaaf** [gojp/goreportcard#80]

**Comment by shawnps** [comment]
Wonder if we can use this https://github.com/ryanuber/go-license/

**Comment by shawnps** [comment]
seems to include copying 

https://github.com/ryanuber/go-license/blob/master/license.go#L33

**Comment by shawnps** [comment]
for now we can probably just try to detect anything in that list, since it's really a yes/no at the moment

**Comment by shawnps** [comment]
Might want to update the frontend to be more clear that it's not just "LICENSE" files we're checking for

**Comment by client9** [comment]
I can provide some code... the list in go-reportcard is kinda outdated.   I wrote some code for godep which which i can repackage for you.

**Comment by shawnps** [comment]
@client9 thanks, or you can point me at where the code is you wrote for godep and I can take a stab also

**Comment by client9** [comment]
```go
// LicenseFilePrefix is a list of filename prefixes that indicate it
//  might contain a software license
var LicenseFilePrefix = []string{
        "licence", // UK spelling
        "license",
        "copying",
        "unlicense",
        "copyright",
        "copyleft",
}

// IsLicenseFile returns true if the filename might be contain a software license
func IsLicenseFile(filename string) bool {
        lowerfile := strings.ToLower(filename)
        for _, prefix := range LicenseFilePrefix {
                if strings.HasPrefix(lowerfile, prefix) {
                        return true
                }
        }
        return false
}
```

**Comment by shawnps** [comment]
@client9 thanks, I added some of the examples from `LicenseFilePrefix`
