### ISSUE TITLE
Exclude go-bindata generated files

### ISSUE THREAD

**Issue by hermanschaaf** [gojp/goreportcard#81]
From [user bbrazil on Reddit](https://www.reddit.com/r/golang/comments/44wduq/show_golang_go_report_card/czti2rt): 

> On https://goreportcard.com/report/github.com/prometheus/prometheus there's a lot of complaints about https://github.com/prometheus/prometheus/blob/master/web/ui/bindata.go which is file generated by go-bindata.
Maybe any files starting with "Code generated by go-bindata." should be excluded?

Sounds good to me.

**Comment by shawnps** [comment]
I've used this tool before as well and I believe it always outputs a bindata.go, so let's just skip those files for now

**Comment by hermanschaaf** [comment]
So should we consider this fixed now?

**Comment by shawnps** [comment]
@hermanschaaf yeah I think so, I'll close
