### ISSUE TITLE
Refresh ignores new commits

### ISSUE THREAD

**Issue by cavaliercoder** [gojp/goreportcard#83]
I've clicked `Refresh` a few times but the report data doesn't reflect my committed code changes. The report timestamp is updated as expected.

The project in question is [github.com/cavaliercoder/grab](https://github.com/cavaliercoder/grab).

For example, [the report](https://goreportcard.com/report/github.com/cavaliercoder/grab) (Last refresh: 2016-02-10T03:37:50.61859419Z) shows that there is no license file, but the license is [clearly committed and present](https://github.com/cavaliercoder/grab/blob/master/LICENSE).

**Comment by shawnps** [comment]
@cavaliercoder thanks for filing an issue.

I'm not sure why but it seems like `go get` wasn't updating your repo on our server. I pulled it manually but I'll leave this open so we can investigate why that might have happened.

**Comment by JaTochNietDan** [comment]
I have the same issue for this one: github.com/teamwork/tnef

**Comment by rikvdh** [comment]
Also the same for github.com/SimpleWebFS/server

**Comment by dnaeon** [comment]
Same issue here as well.

* https://github.com/dnaeon/go-vcr

**Comment by hermanschaaf** [comment]
Yes, strange. We are using `go get` with the `-u` flag now, but somehow it is still not updating. Not sure why yet...

**Comment by hermanschaaf** [comment]
It should be fixed now, after just deploying https://github.com/gojp/goreportcard/commit/808460fd3dae8c5f8a12f2262fedae262c6c08d4

Please re-open this issue if you run into the same problem again. Thanks everyone for reporting!
