### ISSUE TITLE
After a force push, the repo cannot be pulled

### ISSUE THREAD

**Issue by thiderman** [gojp/goreportcard#87]
I was fixing some errors to get a perfect score. I fixed'em and pushed'em and almost all was well. Eagerly waiting for my report card to tell me how fantastic I am, I pressed the `Refresh` button. Alas, I just got 90% on `gofmt` score! Blast! Apparently I forgot to `git add` the changes to one of my last files. I fixed this and force pushed. Excited as a kid on Christmas, I reapplied pressure to the aforementioned button, but was greeted with a yellow bar on top of the page saying that my code cannot be pulled. Tears were shed, hearts were broken, and agony was everywhere.

I suspect that whatever caching mechanism you are using doesn't really approve of the terrible and awful practice that is force pushing. Of course, scoundrels like myself should stop doing it, but let's face it - it's going to happen every now and again. Perhaps you can add some handling to this woeful case of error?

The repo in question is [thiderman/towerfall](https://github.com/thiderman/towerfall), report available [here](https://goreportcard.com/report/github.com/thiderman/towerfall). If I can provide any further info I'd be happy to do so!

Also cheers for a fun and useful project!

**Comment by hermanschaaf** [comment]
We use nothing more complicated than `go get -u -d ...`, which fails in this case with an error indicating that the local cached copy diverged from the upstream master. 

So I just pushed some changes to fix this. In [9edfe29](https://github.com/gojp/goreportcard/commit/9edfe29b03438718cf59743ef42d482bcb9d1dd3), we try `go get` first. If it fails, we delete the cached directory, and try `go get` a second time. Failing that, we give up. This should also fix the case where a remote repo (on Github, Bitbucket, etc) gets deleted and replaced with another project. 

Thanks for reporting @thiderman, and congratulations on your [A+, 100% report card](https://goreportcard.com/report/github.com/thiderman/towerfall)!

**Comment by thiderman** [comment]
Very nice with a quick fix, and yay for the perfect score! :dancer: 

Thanks again! :smile:
