### ISSUE TITLE
Allow British English rather than American for Misspell

### ISSUE THREAD

**Issue by DanielOaks** [gojp/goreportcard#88]
I've got a package that uses British English rather than American, so misspell knocks off a few points because of it. It'd be awesome if there was a way to signify that British (or even Australian) English should be used rather than American.

Example package: https://goreportcard.com/report/github.com/DanielOaks/girc-go

I believe this issue on misspell might also be related, might need to wait for upstream to add an option before you could do anything about it: https://github.com/client9/misspell/issues/6

Thanks for creating this awesome site! It's a good way to have a quick, clean overview of your package and the issues with it. Has helped me find and fix some silly issues.

**Comment by client9** [comment]
hi @DanielOaks I'll work on adding a .misspell.yaml like file you can add in.  That will allow you to configure some options. thx

nickg (the misspell guy)

**Comment by DanielOaks** [comment]
Awesome, thanks @client9, much appreciated!

**Comment by client9** [comment]
Actually @DanielOaks  if you have noticed misspell "corrections" from UK to USA could you file a ticket or update one listing the ones that need removing.  I tried to get rid of some of them, but I'm sure there are others.

**Comment by client9** [comment]
Hi @DanielOaks misspell has a been fixed so it is neutral English.    Please let us know if re-running goreportcard fixes the immediate issue.

Later we'll make it possible to select if you want US, CA, GB-ise or GB-ize (or any other variation) so you have consistent English.. no matter where you are!

thanks for the report.

**Comment by shawnps** [comment]
@DanielOaks I'm going to go ahead and close since it looks like your repo has no more misspell issues, thanks! Feel free to make another ticket if something else comes up.

**Comment by DanielOaks** [comment]
All fine now, thanks very much for the fast turnaround!
