### ISSUE TITLE
idea: Branch switching?

### ISSUE THREAD

**Issue by hako** [gojp/goreportcard#96]
It would be great if goreportcard can run on different git branches of a Go project. We could list all the branches in a repo, switch to that branch and run goreportcard on it.

**Comment by shawnps** [comment]
@marians said:

> I don't see an option to check an arbitrary branch of a git repository. However that would be quite helpful as a quality insurance step before merging a PR into master.

@onuryilmaz said:

> I think this feature could help a lot:
> - Listen for Github hooks on PR events
> - Run checks and save result on a temporary URL (since it would be clicked from merge checks)
> - Write response to PR check (for merge checks)

**Comment by johnfercher** [comment]
Any news about this feature?

**Comment by shawnps** [comment]
@johnfercher thanks for bringing this back to our attention. I'm discussing with @hermanschaaf but unfortunately we don't have much time recently to work on new features. Hopefully we will find some time in the future. 

It's possible we will make it available to supporters at https://www.patreon.com/goreportcard.

**Comment by arkn98** [comment]
Is this issue still open? Can I work on it?

**Comment by paullaffitte** [comment]
Since the default branch on github is now `main`, it would be quite useful to be able to specify the branch name.
