### ISSUE TITLE
Improve scoring algorithm

### ISSUE THREAD

**Issue by hermanschaaf** [gojp/goreportcard#98]
The current algorithm, iirc, works more or less like this:
- get the total number of files, `t`
- for each kind of error, count the number of files containing at least one error, `e1`, `e2`, ... `eN`
- define a weight for each error type (e.g. `gofmt` is weighted more heavily than `go vet`), `w1`, `w2` ... `wN`
- final score is `(w1 * e1 + w2 * e2 + ... + wN * eN) / t`

This means that even when a file has 10,000 lines but only one error, it gets scored the same as a file with 10 lines and one error. This seems incorrect, and I think we should bring line counts into the equation. Instead of counting files, count the total number of lines of Go files in the project, `l` (exclude empty lines). And instead of counting the number of files containing one error, count the total number of errors for each type, `et1`, `et2` ... `etN`. Now:
- final score is `(w1 * et1 + w2 * et2 + ... + wN * etN) / l`

This will lead to a score that represents the proportion of lines containing errors, with each error still weighted by severity. To get a score of 0%, you would have to really go out of your way to make every type of error occur on every line. And even to get a score of 90%, you would need to have a lot of errors. So finally I propose adding an exponent to all this, `x`:
- final score is `((w1 * et1 + w2 * et2 + ... + wN * etN) / l) ^ x`

We might want to play around to find an exponent that feels right, but `3` seems like a good place to start. So if you got 99% of lines without errors, your score would be adjusted to 97%. If you got 95% of lines, it would be adjusted to 85.7%, and 90% would be 72.9%, so it decreases rapidly. 

The only thing is that we to calculate and store the line count of projects first, and we'll need a script to retroactively adjust the scores of all projects in the cache. Then we can change the formula and play with exponent values.

Any thoughts / feedback?

**Comment by shawnps** [comment]
@hermanschaaf doing it by line count sounds fine to me. I think you know something about doing that? :wink: 

https://github.com/gengo/goloc

**Comment by shawnps** [comment]
I do wonder how much slower it'll be though.

**Comment by hermanschaaf** [comment]
oh yeah, I completely forgot I even wrote goloc, haha. :smirk:  We could use the `CountStatements` function from there. I don't think it's going to slow down the process too much, but it is quite a lot of work to change all this, also retro-actively.

**Comment by shawnps** [comment]
recent relevant issue:

https://github.com/gojp/goreportcard/issues/173
